/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

import {
    PUBLIC_GET_TWEET,
    PUBLIC_GET_TWEET_STATS,
    PRIVATE_GET_TIMELINE,
    PUBLIC_GET_TWEETS,
    PRIVATE_GET_NOTIFICATIONS,
    PUBLIC_POST_UNLIKE,
    PRIVATE_POST_TWEET,
    PUBLIC_POST_REPLY,
    PUBLIC_GET_FOLLOWEES,
    PUBLIC_GET_REPLY,
    PRIVATE_GET_STATS,
    PUBLIC_DELETE_REPLY,
    PRIVATE_DELETE_TWEET,
    PRIVATE_POST_USER,
    PUBLIC_POST_UNFOLLOW,
    PUBLIC_GET_USER,
    PUBLIC_GET_USERS,
    PUBLIC_GET_WHOTOFOLLOW,
    PUBLIC_GET_REPLIES,
    PUBLIC_GET_FOLLOWERS,
    PUBLIC_POST_FOLLOW,
    PUBLIC_POST_LIKE,
    PUBLIC_POST_RETWEET,
    PUBLIC_POST_UNRETWEET,
    PUBLIC_POST_CHAT,
    PRIVATE_DELETE_CHAT,
    PRIVATE_GET_CHATS,
    PRIVATE_GET_CHAT,
    PRIVATE_GET_MESSAGES,
    PUBLIC_POST_MESSAGE,
    PRIVATE_GET_MESSAGE,
    PUBLIC_DELETE_MESSAGE,
    PRIVATE_POST_UPLOAD_IMAGE,
    PUBLIC_GET_IMAGE,
    PRIVATE_POST_LOGIN
} from "@/service/service";
import {generateUUID} from "@/lib/uuid";


// [MOCK] window.go.main.App.Call({"path":"/private/get/notifications/0.0.0","body":{"limit":20,"cursor":""},
// "message_id":"3e5c6206-b4c6-4418-882e-4c06c6b070b0","node_id":"None","timestamp":"2025-10-21T12:15:12.628Z"})
if (process.env.NODE_ENV === 'development') {
    console.warn("⚠️ Running in standalone mode — mocking window.go");

    window.go = {
        main: {
            App: {
                Call: (arg1) => {
                    console.log(`[MOCK] window.go.main.App.Call(${JSON.stringify(arg1)})`);
                    const body = generateResponse(arg1);
                    console.log(`[MOCK] window.go.main.App.Response(${JSON.stringify(body)})`);

                    return Promise.resolve({body:body});
                }
            }
        }
    };
}

const mockUser = {
    avatar_key: "image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA", // MIME + base64
    background_image_key: "image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD",
    bio: "Developer and p2p enthusiast. Building WarpNet.",
    birthdate: "1988-04-15",
    created_at: "2025-01-01T12:00:00Z",
    updated_at: "2025-10-21T10:30:00Z",
    followees_count: 0,
    followers_count: 0,
    id: "7f4c2a91-d03e-4de5-a0a7-8429bdf17fa8",
    isOffline: false,
    node_id: "node-12aa3bb4",
    network: "warpnet",
    latency: 0,
    tweets_count: 1,
    username: "Vadim",
    website: "https://warp-net.github.io/",
    moderation: {is_ok: true},
    metadata: {
        theme: "dark",
        locale: "en-US",
        verified: "true",
        join_method: "invite",
    },
};

const mockTweet = {
    created_at: "2025-10-20T14:25:00Z",
    updated_at: "2025-10-21T09:10:00Z",
    id: "8a21e4d5-912f-4f13-a7d3-8b7d6a1a51d1",
    parent_id: null,
    retweeted_by: null,
    root_id: "8a21e4d5-912f-4f13-a7d3-8b7d6a1a51d1",
    text: "WarpNet update: new decentralized feed algorithm! 🚀 #p2p #WarpNet",
    user_id: mockUser.id,
    username: mockUser.username,
    image_key: "image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA",
    network: "warpnet",
    moderation: {is_ok: true},
};


function generateResponse(arg) {
    console.log()
    switch (arg.path) {
    case PRIVATE_POST_LOGIN:
        let user_id = mockUser.id
        if (arg.user_id) {
            user_id = arg.user_id
        }
        const owner = {username: arg.body.username, node_id: arg.node_id, user_id: user_id, created_at: Date.now()}
        mockUser.username = arg.body.username
        return {identity: {token: generateUUID(), owner: owner}}
    case PUBLIC_GET_USER:
        return mockUser
    case PRIVATE_GET_TIMELINE:
        const tweets = [mockTweet]
        return {cursor: arg.cursor, user_id: arg.user_id, tweets: tweets}
    default:
        return {code:0,message:"Accepted"};
    }
}