<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->

<template>
  <div id="app" class="flex container h-full w-full" v-scroll:bottom="loadMore">
    <div class="flex container h-full w-full">
      <SideNav />

      <div class="w-full sm:w-1/3 md:w-1/2 lg:w-1/2 h-full overflow-y-scroll no-scrollbar hidden md:block">
        <div class="px-5 py-3 border-b border-lighter flex">
          <h1 class="text-xl font-bold flex-1">Chats</h1>
          <i class="fas fa-cog text-xl text-blue cursor-pointer"></i>
          <i @click="newMessage()" class="fas fa-plus-circle ml-3 text-xl text-blue cursor-pointer"></i>
        </div>

        <!-- chats -->
        <Loader :loading="loading" />
        <div v-if="!loading">
          <div v-if="chats.length === 0" class="flex flex-col items-center justify-center w-full pt-10">
            <div class="w-1/2 flex flex-col items-center justify-center">
              <p class="font-bold text-lg">No chats yet</p>
              <p class="text-sm text-dark">
                Wait until someone starts a chat here.
              </p>
            </div>
          </div>
          <div v-for="chat in chats" :key="chat.id">
            <div v-if="(getUser(chat.other_user_id))">
              <div class="cursor-pointer">
                <div class="w-full p-2 pt-1 pb-1 md:p-4 md:pt-2 md:pb-2 border-b hover:bg-lightest flex"
                  @click="selectChat(chat)">
                  <div class="flex-none mr-2 md:mr-4 pt-1">
                    <a :href="`#/${chat.other_user_id}`">
                      <img :src="getUser(chat.other_user_id).avatar || 'default_profile.png'"
                           class="flex-none w-12 h-12 rounded-full"  />
                    </a>
                  </div>
                  <div class="w-full truncate">
                    <div class="flex items-center w-full">
                      <p class="font-semibold">{{ getUser(chat.other_user_id).username || 'Anonymous' }}</p>
                      <p class="hidden md:block text-sm text-dark ml-2 truncate">
                        @{{ chat.other_user_id }}
                      </p>
                      <p class="text-sm text-dark ml-auto">
                        {{ $filters.timeago(chat.lastModified) }}
                      </p>
                    </div>
                    <p class="pb-2 truncate" v-linkify>{{ chat.last_message || "" }}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="w-full border-l border-r border-lighter h-screen flex items-center justify-center">
        <div class="text-center">
          <h2 class="text-2xl font-bold mb-4">Select a chat</h2>
          <p class="text-gray-600">Choose a chat from the list to start chatting</p>
        </div>
      </div>

      <NewMessageOverlay
        v-if="showNewMessageModal"
        v-model:showNewMessageModal="showNewMessageModal"
        :profileId="profileId"
        @selected="selected"
      />
    </div>
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: "Chats",
  components: {
    NewMessageOverlay: defineAsyncComponent(() => import('../components/NewMessageOverlay.vue')),
    Loader: defineAsyncComponent(() => import('../components/Loader.vue')),
    SideNav: defineAsyncComponent(() => import('../components/SideNav.vue')),
  },
  data() {
    return {
      loading: true,
      showNewMessageModal: false,
      chats: [],
      profileId: "",
      usersMap: new Map(),
      otherUser: undefined,
    };
  },
  methods: {
    newMessage() {
      this.showNewMessageModal = true;
    },
    async selectChat(chat) {
      if (!chat || chat.id.length === 0) {
        return
      }
      console.log('selectChat()')
      this.$router.push({
        name: 'Messages',
        params: {
          id: this.$route.params.id,
          chatId: chat.id,
        },
      });
    },
    async selected(user) {
      console.log('selected()')
      if (!user || user.id.length === 0) {
        return;
      }
      this.showNewMessageModal = false;

      // Check if chat already exists
      const existingChat = this.chats.find(
        conv => conv.other_user_id === user.id
      );

      if (existingChat) {
        await this.selectChat(existingChat);
        return;
      }
      // Create new chat
      const newChat = await warpnetService.createChat(user.id);
      await this.selectChat(newChat);
    },
    getUser(userId) {
      return this.usersMap.get(userId);
    },
    async loadChatUser(userId) {
      if (!userId || userId.length === 0) {
        return
      }

      const u = await warpnetService.getProfile(userId)
      u.avatar = await warpnetService.getImage({userId:u.id, key:u.avatar_key})
      this.usersMap.set(u.id, u)
      console.log('usersMap', this.usersMap)
    },
    async loadMore() {
      const chats = await warpnetService.getChats(false);
      for (const chat of chats) {
        await this.loadChatUser(chat.other_user_id)
        await this.loadChatUser(chat.owner_id)
      }
      this.chats = [...this.chats, ...chats];
    },
  },

  async created() {
      console.log("loading component:", this.$options.name);
      this.profileId = this.$route.params.id
      await this.loadChatUser(this.profileId)

      const chats = await warpnetService.getChats(true);

      for (const chat of chats) {
        await this.loadChatUser(chat.owner_id)
        await this.loadChatUser(chat.other_user_id)

        if (chat.owner_id !== this.profileId) {
          [chat.owner_id, chat.other_user_id] = [chat.other_user_id, chat.owner_id];
        }
      }
      this.chats = chats;
      this.loading = false;
    }
};
</script>
