<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div class="flex container h-full w-full">
    <SideNav />
    
    <div class="flex-1 flex flex-col h-full">
      <div class="px-4 py-3 border-b border-lighter flex items-center">
        <router-link :to="{ name: 'Chats' }" class="mr-4">
          <i class="fas fa-arrow-left text-xl text-blue"></i>
        </router-link>
        
        <div v-if="chat" class="flex items-center">
          <img :src="otherUser.avatar || 'default_profile.png'"
               class="w-10 h-10 rounded-full mr-3" />
          <div>
            <p class="font-bold">{{ otherUser.username }}</p>
            <p class="text-sm text-dark">@{{ chat.other_user_id }}</p>
          </div>
        </div>
      </div>

      <!-- Messages -->
      <div class="flex-1 overflow-y-auto p-4" ref="messageContainer">
        <div v-if="loading" class="flex justify-center">
          <Loader :loading="loading" />
        </div>

        <template v-else>
          <div v-for="message in messages" :key="message.id" 
               class="mb-4 flex"
               :class="{'justify-end': message.sender_id === currentUserId}">
            <div class="max-w-3/4 rounded-lg px-4 py-2"
                 :class="message.sender_id === currentUserId ?
                        'bg-blue text-white' : 'bg-lighter'">
              <p v-linkify>{{ message.text }}</p>
              <p class="text-xs mt-1 text-gray-500">
                {{ $filters.timeago(message.created_at) }}
              </p>
            </div>
          </div>
        </template>
      </div>

      <!-- Message Input -->
      <div class="border-t border-lighter px-4 py-3">
        <form @submit.prevent="sendMessage" class="flex">
          <input v-model="newMessage" 
                 type="text"
                 placeholder="Type a message..."
                 class="flex-1 rounded-full border border-lighter px-4 py-2 mr-2" />
          <button type="submit" 
                  class="bg-blue text-white rounded-full px-6 py-2">
            Send
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: 'Chat',
  components: {
    SideNav: defineAsyncComponent(() => import('../components/SideNav.vue')),
    Loader: defineAsyncComponent(() => import('../components/Loader.vue')),
  },
  data() {
    return {
      loading: true,
      chat: null,
      messages: [],
      newMessage: '',
      chatId: undefined,
      currentUserId: undefined,
      otherUser: undefined,
    };
  },
  methods: {
    async loadChat() {
      try {
        this.chat = await warpnetService.getChat({
          chatId: this.chatId
        });
      } catch (error) {
        console.error('Error loading chat:', error);
      }
    },

    async loadMessages() {
      try {
        const messages = await warpnetService.getDirectMessages(
            {chatId:this.chatId, cursorReset:true},
        );

        this.messages = [...messages, ...this.messages];
      } catch (error) {
        console.error('Error loading messages:', error);
      }
    },

    async sendMessage() {
      if (!this.newMessage.trim()) return;

      try {
        const message = await warpnetService.sendDirectMessage( {
          chatId: this.chatId,
          receiverId: this.otherUser.id,
          text: this.newMessage,
        });
        this.messages.push(message);
        this.newMessage = '';
        this.scrollToBottom();
      } catch (error) {
        console.error('Error sending message:', error);
      }
    },

    scrollToBottom() {
      this.$nextTick(() => {
        const container = this.$refs.messageContainer;
        container.scrollTop = container.scrollHeight;
      });
    }
  },
  async created() {
    console.log("loading component:", this.$options.name);
    this.currentUserId = this.$route.params.id;
    this.chatId = this.$route.params.chatId;

    await Promise.all([
      this.loadChat(),
      this.loadMessages()
    ]);

    if (this.chat.owner_id !== this.currentUserId) {
      this.otherUser = await warpnetService.getProfile(this.chat.owner_id)
    } else {
      this.otherUser = await warpnetService.getProfile(this.chat.other_user_id)
    }
    this.otherUser.avatar = await warpnetService.getImage({userId:this.otherUser.id, key:this.otherUser.avatar_key})
    this.loading = false;
    this.scrollToBottom();
  }
};
</script>