<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="flex container h-screen w-full">
    <div class="flex container h-screen w-full">
      <SideNav />

      <div class="w-full h-full overflow-y-scroll no-scrollbar">
        <div class="px-5 pt-3 flex items-center">
          <button
            @click="gotoProfile()"
            class="rounded-full p-3 px-4 focus:outline-none hover:bg-lightblue"
          >
            <i class="fas fa-arrow-left text-blue"></i>
          </button>
          <div class="lg:block ml-4">
            <h1 class="text-xl font-bold">{{ profile?.username }}</h1>
            <p class="text-left text-sm leading-tight text-dark">
              @{{ profile?.id }}
            </p>
          </div>
        </div>

        <div class="flex flex-row justify-evenly mt-2">
          <button
            class="w-1/2 text-dark font-bold border-b-2 border-blue px-10 py-4 hover:bg-lightblue"
          >
            Followers
          </button>
          <button
            @click="goToFollowing()"
            class="w-1/2 text-dark font-bold border-b-2 px-10 py-4 hover:bg-lightblue"
          >
            Following
          </button>
        </div>

        <Loader :loading="loading" />
        <Users v-if="profiles" :users="profiles" :loading="loading" />
      </div>

      <div
        class="hidden md:block w-1/3 z-0 h-full border-l border-lighter px-6 py-2 overflow-y-scroll no-scrollbar relative"
      >
        <SearchBar />
      </div>
    </div>
  </div>
</template>

<script>
import SideNav from "../components/SideNav.vue";
import SearchBar from "../components/SearchBar.vue";
import Users from "../components/Users.vue";
import Loader from "../components/Loader.vue";
import {warpnetService} from "@/service/service";
import user from "@/components/User.vue";

export default {
  name: "Followers",
  components: {
    SideNav,
    SearchBar,
    Users,
    Loader,
  },
  data() {
    return {
      loading: true,
      profile: undefined,
      profiles: [],
    };
  },
  methods: {
    gotoProfile() {
      this.$router.push({
        name: "Profile",
        params: {
          id: this.profile.id,
        },
      });
    },
    goToFollowing() {
      this.$router.push({
        name: "Following",
        params: {
          id: this.profile.id,
        },
      });
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);

    if (this.profiles.length > 0) {
      this.loading = false;
    }

    const profileId = this.$route.params.id;
    if (!profileId) {
      throw new Error('Profile ID is required');
    }

    this.profile = await warpnetService.getProfile(profileId);
    this.profiles = await warpnetService.getUsers({profileId:profileId, cursorReset:true})
    this.loading = false;
  },
};
</script>
