<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="flex container h-screen w-full">
    <!-- side navigation -->
    <SideNav />

    <!-- timeline -->
    <div
      class="w-full h-full overflow-y-scroll no-scrollbar"
      v-scroll:bottom="loadMore"
    >
      <div
        class="px-5 py-3 border-b border-lighter flex items-center justify-between"
      >
        <h1 class="text-xl font-bold">Home</h1>
        <button
            @click="toggleInfo"
            class="text-xl text-blue cursor-pointer hover:bg-lighter rounded-full w-9 h-9 flex items-center justify-center"
            aria-label="Show node info"
            type="button"
        >
          <i class="fas fa-info-circle" aria-hidden="true"></i>
        </button>
      </div>
      <div class="px-5 py-3 border-b-8 border-lighter flex">
        <div v-if="profile" class="flex-none mr-4">
          <img
            :src="profile.avatar || '/default_profile.png'"
            class="flex-none w-12 h-12 rounded-full"

          />
        </div>
        <div class="w-full relative">
          <label for="compose-tweet" class="sr-only">Compose a tweet</label>
          <textarea
            id="compose-tweet"
            v-model="tweet.text"
            placeholder="What's happening?"
            class="w-full focus:outline-none mt-3 pb-3"
          ></textarea>
          <div v-if="imageAttachment" class="relative mt-4 inline-block">
            <img
                :src="imageAttachment"
                alt="Image preview"
                class="w-32 h-32 object-cover rounded border border-lighter"
            />
            <button
                @click="removeImageAttachment"
                type="button"
                class="absolute top-0 right-0 mt-2 mr-2 bg-white bg-opacity-75 rounded-full p-1 hover:bg-red-500"
                title="Remove image"
            >
              <i class="fas fa-times text-red-600 hover:text-white"></i>
            </button>
          </div>
          <div>
            <button
                @click="openFileInput('imageUrlFileInput')"
                class="text-lg text-blue mr-3 rounded-full w-9 h-9 flex items-center justify-center hover:bg-lightblue"
                type="button"
                aria-label="Attach image"
            >
              <i class="far fa-image" aria-hidden="true"></i>
              <input
                  @change="fileChange('imageUrlFileInput')"
                  ref="imageUrlFileInput"
                  accept="image/*"
                  type="file"
                  class="hidden"
              />
            </button>
            <button type="button" disabled class="text-lg text-blue mr-3 rounded-full w-9 h-9 flex items-center justify-center opacity-50 cursor-not-allowed" aria-label="Attach video (coming soon)" title="Coming soon">
              <i class="fas fa-film" aria-hidden="true"></i>
            </button>
            <button type="button" disabled class="text-lg text-blue mr-3 rounded-full w-9 h-9 flex items-center justify-center opacity-50 cursor-not-allowed" aria-label="Add poll (coming soon)" title="Coming soon">
              <i class="far fa-chart-bar" aria-hidden="true"></i>
            </button>
            <button type="button" disabled class="text-lg text-blue mr-3 rounded-full w-9 h-9 flex items-center justify-center opacity-50 cursor-not-allowed" aria-label="Add emoji (coming soon)" title="Coming soon">
              <i class="far fa-smile" aria-hidden="true"></i>
            </button>
          </div>
          <button
            @click="addNewTweet"
            type="button"
            class="h-10 px-4 text-white font-semibold bg-blue hover:bg-darkblue rounded-full absolute bottom-0 right-0"
            :class="tweet.text ? '' : 'opacity-50 cursor-not-allowed'"
            :disabled="!tweet.text"
          >
            Tweet
          </button>
        </div>
      </div>

      <!-- timeline -->
      <Loader :loading="loading" />
      <div
        v-if="!loading && timeline.length === 0"
        class="flex flex-col items-center justify-center w-full pt-10 px-6"
      >
        <p class="font-bold text-lg">Welcome to Warpnet!</p>
        <p class="text-sm text-dark text-center">
          This is the best place to see what's happening in your world. Find
          some people and topics to follow now.
        </p>
        <button
          class="text-white bg-blue rounded-full font-semibold mt-4 px-4 py-2 hover:bg-darkblue"
        >
          <p class="hidden lg:block">Let's go!</p>
          <i class="fas fa-plus lg:hidden"></i>
        </button>
      </div>
      <Tweets :tweets="timeline" />
    </div>
    <InfoOverlay
        :visible="showInfo"
        :content="infoContent"
        :position="infoPosition"
    />
    <!-- Toast notifications -->
    <div v-if="toastMessage" class="toast-container">
      <div :class="['toast', toastType === 'error' ? 'toast-error' : 'toast-success']" role="alert">
        <i :class="toastType === 'error' ? 'fas fa-exclamation-circle' : 'fas fa-check-circle'" aria-hidden="true"></i>
        {{ toastMessage }}
      </div>
    </div>
    <!-- default right bar -->
    <DefaultRightBar
        :profile="profile"
    />
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: "Home",
  components: {
    SideNav: defineAsyncComponent(() => import('@/components/SideNav.vue')),
    DefaultRightBar: defineAsyncComponent(() => import('@/components/DefaultRightBar.vue')),
    Tweets: defineAsyncComponent(() => import('@/components/Tweets.vue')),
    Loader: defineAsyncComponent(() => import('@/components/Loader.vue')),
    InfoOverlay: defineAsyncComponent(() => import('@/components/InfoOverlay.vue')),
  },
  data() {
    return {
      tweet: {
        text: "",
        root_id: "",
        image_key: "",
      },
      loading: true,
      profile: {},
      timeline: [],
      showInfo: false,
      infoContent: '',
      infoPosition: { top: '0px', left: '0px' },
      imageAttachment: undefined,
      videoAttachment: undefined,
      toastMessage: '',
      toastType: 'error',
      toastTimeoutId: null,
    };
  },
  methods: {
    openFileInput(ref) {
      this.$refs[ref].click();
    },
    async fileChange(ref) {
      const file = this.$refs[ref].files[0];
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => this.imageAttachment = reader.result;
      reader.onerror = (error) => {
        console.error("Error reading file", error);
        this.showToast('Error reading file. Please try again.', 'error');
      };
    },
    async removeImageAttachment() {
      this.imageAttachment = undefined
    },
    async addNewTweet() {
      if (!this.tweet.text) return;
      if (this.imageAttachment) {
        this.tweet.image_key = await warpnetService.uploadImage(this.imageAttachment)
      }

      await warpnetService.createTweet({text: this.tweet.text, imageKey: this.tweet.image_key});

      this.tweet.text = "";
      this.tweet.image_key = "";
      this.imageAttachment = undefined;

      this.timeline = await warpnetService.getMyTimeline(true);
    },
    async loadMore() {
      const timeline = await warpnetService.getMyTimeline(false);
      this.timeline = this.timeline.concat(timeline);
    },
    async toggleInfo(event) {
      if (this.showInfo) {
        this.showInfo = false;
        return;
      }

      this.infoContent = await this.getInfo();

      const rect = event.currentTarget.getBoundingClientRect();
      this.infoPosition = {
        top: `${rect.bottom + window.scrollY}px`,
        left: `${rect.left + window.scrollX}px`,
      };

      this.showInfo = true;
    },
    async getInfo() {
      return await warpnetService.getNodeInfo();
    },
    showToast(message, type = 'error') {
      if (this.toastTimeoutId) clearTimeout(this.toastTimeoutId);
      this.toastMessage = message;
      this.toastType = type;
      this.toastTimeoutId = setTimeout(() => {
        this.toastMessage = '';
        this.toastTimeoutId = null;
      }, 4000);
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);

    this.profile = warpnetService.getOwnerProfile();

    this.profile.background_image = await warpnetService.getImage(
        {userId:this.profile.user_id, key:this.profile.background_image_key},
    );
    this.profile.avatar = await warpnetService.getImage(
        {userId:this.profile.user_id, key:this.profile.avatar_key},
    )

    this.timeline = await warpnetService.getMyTimeline(true);
    this.loading = false;
  },
  beforeUnmount() {
    if (this.toastTimeoutId) {
      clearTimeout(this.toastTimeoutId);
      this.toastTimeoutId = null;
    }
  },
};
</script>