<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="flex h-full w-full">
    <!-- Sidebar -->
    <SideNav />

    <!-- Chats list (center column) -->
    <div class="hidden md:flex flex-col w-1/3 h-full overflow-y-scroll border-r border-lighter">
      <div class="px-5 py-3 border-b border-lighter flex items-center">
        <h1 class="text-xl font-bold flex-1">Chats</h1>
        <i class="fas fa-cog text-xl text-blue cursor-pointer"></i>
        <i @click="newMessage()" class="fas fa-plus-circle ml-3 text-xl text-blue cursor-pointer"></i>
      </div>

      <Loader :loading="loading" />

      <template v-if="!loading">
        <div v-if="chats.length === 0" class="flex flex-col items-center justify-center pt-10">
          <p class="font-bold text-lg">No chats yet</p>
          <p class="text-sm text-dark">Wait until someone starts a chat here.</p>
        </div>

        <div v-for="chat in chats" :key="chat.id"
             class="cursor-pointer"
             :class="chat.id === active?.id ? 'border-r-2 border-blue' : ''"
             @click="selectChat(chat)">
          <div class="flex items-start px-4 py-2 hover:bg-lightest border-b">
            <div class="mr-4">
              <img
                  :src="getUser(chat.other_user_id)?.avatar || 'default_profile.png'"
                  class="h-12 w-12 rounded-full"
              />
            </div>
            <div class="w-full truncate">
              <div class="flex items-center">
                <p class="font-semibold truncate">{{ getUser(chat.other_user_id)?.username || 'Anonymous' }}</p>
                <p class="text-sm text-dark ml-2 truncate hidden md:block">
                  @{{ chat.other_user_id }}
                </p>
                <p class="text-sm text-dark ml-auto">
                  {{ $filters.timeago(chat.updated_at) }}
                </p>
              </div>
              <p class="text-sm truncate" v-linkify>{{ chat.last_message || '' }}</p>
            </div>
          </div>
        </div>
      </template>
    </div>

    <!-- Placeholder (right column, if no active chat selected) -->
    <div v-if="loading || !active" class="flex flex-col w-full md:w-2/3 h-full items-center justify-center">
      <div class="w-3/5 text-center">
        <p class="font-bold text-lg">You don’t have a message selected</p>
        <p class="text-sm text-dark mt-2">
          This is where you’ll see messages from people you don’t follow.
        </p>
        <button
            @click="newMessage()"
            class="mt-5 h-10 px-4 text-white font-semibold bg-blue hover:bg-darkblue rounded-full"
        >
          New Message
        </button>
      </div>
    </div>

    <!-- Messages view -->
    <div v-if="!loading && active" class="flex flex-col w-full md:w-2/3 h-full">
      <!-- Top bar -->
      <div class="flex items-center px-5 py-2 border-b border-lighter bg-white sticky top-0">
        <button @click="gotoHome()" class="block md:hidden mr-2 focus:outline-none">
          <i class="fas fa-arrow-left text-blue"></i>
        </button>
        <div class="mr-4">
          <img
              :src="getUser(active.other_user_id)?.avatar || 'default_profile.png'"
              class="w-6 h-6 rounded-full"
          />
        </div>
        <div class="flex flex-col">
          <h1 class="font-bold">{{ getUser(active.other_user_id)?.username }}</h1>
          <p class="text-xs text-dark">@{{ active.other_user_id }}</p>
        </div>
        <i class="fas fa-info-circle ml-auto text-xl text-blue cursor-pointer"></i>
      </div>

      <!-- Messages -->
      <div class="flex-1 overflow-y-scroll px-5 pt-5 no-scrollbar" v-scroll:top="loadMore">
        <div class="flex flex-col-reverse">
          <div ref="scrollToMe"></div>
          <div v-for="message in messages" :key="message.id">
            <!-- Own message -->
            <div v-if="message.sender_id === ownerProfile.id" class="flex justify-end mb-4">
              <div class="bg-blue text-white py-2 px-4 rounded-tl-3xl rounded-bl-3xl rounded-tr-xl">
                {{ message.text }}
              </div>
              <p class="text-xs text-dark ml-2">{{ $filters.time(message.created_at) }}</p>
            </div>
            <!-- Incoming message -->
            <div v-else class="flex items-start mb-4">
              <img
                  :src="getUser(active.other_user_id)?.avatar || 'default_profile.png'"
                  class="h-8 w-8 rounded-full mr-2"
              />
              <div class="bg-lighter text-black py-2 px-4 rounded-tr-3xl rounded-tl-xl rounded-br-3xl">
                {{ message.text }}
              </div>
              <p class="text-xs text-dark ml-2">{{ $filters.time(message.created_at) }}</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Input -->
      <div class="px-5 py-3 border-t border-lighter flex items-center bg-white">
        <input
            v-model="text"
            type="search"
            class="flex-1 px-4 py-2 rounded-full bg-lighter focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue text-sm"
            placeholder="Start a new message"
            @keyup.enter="sendMessage"
            :disabled="disabled"
        />
        <button
            @click="sendMessage"
            :disabled="disabled || !text.length"
            class="ml-4 w-8 h-8 rounded-full focus:outline-none"
            :class="text.length === 0 ? 'opacity-50 cursor-default' : 'hover:bg-lightblue'"
        >
          <i class="fas fa-arrow-right text-blue text-xl"></i>
        </button>
      </div>
    </div>

    <!-- New message overlay -->
    <NewMessageOverlay
        :profileId="active?.other_user_id"
        v-if="showNewMessageModal"
        v-model:showNewMessageModal="showNewMessageModal"
        @selected="selected"
    />
  </div>
</template>


<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: "Messages",
  components: {
    SideNav: defineAsyncComponent(() => import('@/components/SideNav.vue')),
    Loader: defineAsyncComponent(() => import('@/components/Loader.vue')),
    NewMessageOverlay: defineAsyncComponent(() => import('@/components/NewMessageOverlay.vue')),
  },
  data() {
    return {
      loading: true,
      disabled: false,
      showNewMessageModal: false,
      chats: [],
      messages: [],
      ownerProfile: undefined,
      active: undefined,
      text: '',
      usersMap: new Map(),
      otherUser: undefined,
    };
  },
  methods: {
    newMessage() {
      this.showNewMessageModal = true;
    },
    gotoHome() {
      this.$router.push({
        name: "Home",
      });
    },
    async sendMessage() {
      if (!this.active.other_user_id || this.text.length === 0) return;
      this.disabled = true; // disable message input temporarily

      const message = await warpnetService.sendDirectMessage({
        chatId: this.active.id,
        receiverId: this.active.other_user_id,
        text: this.text,
      })
      this.messages = [message, ...this.messages]
      this.text = "";
      this.disabled = false;
      await this.$nextTick(() => {
        this.scrollToEnd();
      });
    },
    scrollToEnd() {
      this.$nextTick(() => {
        const el = this.$refs.scrollToMe;
        if (el) {
          el.scrollIntoView({ behavior: "smooth" });
        }
        if (!this.$refs.input) {
          return
        }
        setTimeout(() => this.$refs.input.focus(), 500);
      });
    },
    async selected(user) {
      if (!this.ownerProfile.id || !user.id) {
        console.log("messages: no selected(user)", this.ownerProfile, user)
        return;
      }
      this.showNewMessageModal = false;

      let currentChat = null
      for (const chat of this.chats) {
        const participants = [chat.owner_id, chat.other_user_id];
        if (participants.includes(this.ownerProfile.id) && participants.includes(user.id)) {
          currentChat = chat;
          break;
        }
      }

      if (!currentChat) {
        currentChat = {
          id: "",
          other_user_id: user.id,
          owner_id: this.ownerProfile.id,
        };
      }
      await this.selectChat(currentChat);
    },
    async selectChat(chat) {
      if (!chat) {
        console.warn("no active chat selected")
        return
      }
      this.messages = []; // reset messages
      this.active = chat;

      this.messages = await warpnetService.getDirectMessages(
          {chatId: chat.id, cursorReset: true},
      );
      this.scrollToEnd();
    },
    deselectAll() {
      this.active = undefined;
    },
    getUser(userId) {
      return this.usersMap.get(userId);
    },
    async loadChatUser(userId) {
      const u = await warpnetService.getProfile(userId)
      u.avatar = await warpnetService.getImage({userId:u.id, key:u.avatar_key})
      this.usersMap.set(u.id, u)
    },
    async loadMore() {
      if (!this.active) return;
      const messagesResp = await warpnetService.getDirectMessages(
          {chatId:this.active.chat.id, cursorReset:false},
      )
      this.messages = [...this.messages, ...messagesResp.messages];
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);
    console.log("messages: route chat id:", this.$route.params.chatId)

    this.ownerProfile = warpnetService.getOwnerProfile()
    await this.loadChatUser(this.ownerProfile.id)

    const chats = await warpnetService.getChats(true)
    if (chats.length === 0) {
      console.warn("messages: chats not found")
      this.loading = false;
      return;
    }

    let activeChat = null
    for (const chat of chats) {
      await this.loadChatUser(chat.owner_id)
      await this.loadChatUser(chat.other_user_id)

      if (chat.id === this.$route.params.chatId) {
        console.log('ACTIVE CHAT', JSON.stringify(chat))
        console.log('ACTIVE CHAT owner', chat.owner_id, "other", chat.other_user_id)
        activeChat = chat
      }
      if (chat.owner_id !== this.ownerProfile.id) {
        [chat.owner_id, chat.other_user_id] = [chat.other_user_id, chat.owner_id];
      }
    }

    this.chats = chats;
    await this.selectChat(activeChat);
    this.loading = false;
  },
};
</script>
