<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="flex container h-screen w-full">
    <div class="flex container h-full w-full">
      <SideNav />

      <div class="w-full md:w-1/2 h-full overflow-y-scroll no-scrollbar">
        <div class="px-5 py-3 border-lighter flex items-center justify-between">
          <button
              @click="gotoHome()"
              class="rounded-full md:pr-2 focus:outline-none hover:bg-lightblue"
          >
            <i class="fas fa-arrow-left text-blue"></i>
          </button>
          <h1 class="text-xl font-bold">Notifications</h1>
          <i class="fas fa-cog text-xl text-blue"></i>
        </div>

        <div class="flex flex-col">
          <div class="flex flex-row justify-evenly text-sm">
            <button
              @click="submit('All')"
              class="w-full text-dark font-bold border-b-2 p-1 md:px-3 md:py-4 hover:bg-lightblue sm:truncate"
              :class="`${this.mode === 'All' ? 'border-blue' : ''}`"
            >
              All
            </button>
            <button
              @click="submit('Mentions')"
              class="w-full text-dark font-bold border-b-2 p-1 md:px-3 md:py-4 hover:bg-lightblue sm:truncate"
              :class="`${this.mode === 'Mentions' ? 'border-blue' : ''}`"
            >
              Mentions
            </button>
          </div>
        </div>

        <!-- notifications -->
        <div v-if="mode === 'All'">
          <div
            v-if="notifications.length === 0"
            class="flex flex-col items-center justify-center w-full pt-10"
          >
            <div class="w-1/2 flex flex-col items-center justify-center">
              <p class="font-bold text-lg">No notifications yet</p>
              <p class="text-sm text-dark">Wait until some get shown here.</p>
            </div>
          </div>

          <div v-for="notification in notifications" :key="notification.id">
            <div
              class="w-full p-4 border-b hover:bg-lightest cursor-pointer"
              @click="goToTweet(notification)"
            >
              <div class="flex flex-row">
                <div class="flex-shrink-0 mr-3">
                  <i
                    v-if="notification.type === 'reply'"
                    class="fas fa-comment text-blue text-xl"
                  ></i>
                  <i
                    v-if="notification.type === 'like'"
                    class="fas fa-heart text-red-600 text-xl"
                  ></i>
                  <i
                    v-if="notification.type === 'retweet'"
                    class="fas fa-retweet text-green-500 text-xl"
                  ></i>
                  <i
                    v-if="notification.type === 'follow'"
                    class="fas fa-user-plus text-blue text-xl"
                  ></i>
                  <i
                    v-if="notification.type === 'mention'"
                    class="fas fa-at text-blue text-xl"
                  ></i>
                </div>
                <div class="flex-grow">
                  <div class="flex items-center mb-2">
                    <img
                      v-if="notification.actor_avatar"
                      :src="notification.actor_avatar || '/default_profile.png'"
                      class="h-8 w-8 rounded-full flex-none mr-2"
                      @click.stop="goToProfile(notification.actor_id)"
                    />
                    <div class="flex-grow">
                      <p class="font-semibold text-sm">
                        {{ notification.actor_username || 'Anonymous' }}
                      </p>
                    </div>
                    <p class="text-sm text-dark ml-auto">
                      {{ $filters.timeago(notification.created_at) }}
                    </p>
                  </div>
                  <div class="ml-10">
                    <p v-if="notification.type === 'like'" class="text-sm text-dark">
                      Liked your tweet
                    </p>
                    <p v-if="notification.type === 'retweet'" class="text-sm text-dark">
                      Retweeted your tweet
                    </p>
                    <p v-if="notification.type === 'reply'" class="text-sm text-dark">
                      Replied to your tweet
                    </p>
                    <p v-if="notification.type === 'follow'" class="text-sm text-dark">
                      Followed you
                    </p>
                    <p v-if="notification.type === 'mention'" class="text-sm text-dark">
                      Mentioned you in a tweet
                    </p>
                    <p v-if="notification.tweet_text" class="mt-2 text-sm text-gray-700 dark:text-gray-300 truncate">
                      {{ notification.tweet_text }}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div v-if="mode === 'Mentions'">
          <div
            v-if="mentionNotifications.length === 0"
            class="flex flex-col items-center justify-center w-full pt-10"
          >
            <div class="w-1/2 flex flex-col items-center justify-center">
              <p class="font-bold text-lg">No mentions yet</p>
              <p class="text-sm text-dark">Wait until some get shown here.</p>
            </div>
          </div>
          <div v-for="notification in mentionNotifications" :key="notification.id">
            <div 
              class="w-full p-4 border-b hover:bg-lightest cursor-pointer"
              @click="goToTweet(notification)"
            >
              <div class="flex flex-row">
                <div class="flex-shrink-0 mr-3">
                  <i class="fas fa-at text-blue text-xl"></i>
                </div>
                <div class="flex-grow">
                  <div class="flex items-center mb-2">
                    <img
                      v-if="notification.actor_avatar"
                      :src="notification.actor_avatar || '/default_profile.png'"
                      class="h-8 w-8 rounded-full flex-none mr-2"
                      @click.stop="goToProfile(notification.actor_id)"
                    />
                    <div class="flex-grow">
                      <p class="font-semibold text-sm">
                        {{ notification.actor_username || 'Anonymous' }}
                      </p>
                    </div>
                    <p class="text-sm text-dark ml-auto">
                      {{ $filters.timeago(notification.created_at) }}
                    </p>
                  </div>
                  <div class="ml-10">
                    <p class="text-sm text-dark mb-1">Mentioned you</p>
                    <p v-if="notification.tweet_text" class="text-sm text-gray-700 dark:text-gray-300">
                      {{ notification.tweet_text }}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- default right bar -->
      <DefaultRightBar />
    </div>
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: "Notifications",
  components: {
    SideNav: defineAsyncComponent(() => import("../components/SideNav.vue")),
    DefaultRightBar: defineAsyncComponent(() => import("../components/DefaultRightBar.vue")),
  },
  data() {
    return {
      loading: false,
      notifications: [],
      profile: {},
      mode: this.$route.query.m || "All",
    };
  },
  computed: {
    mentionNotifications() {
      return this.notifications.filter(n => n.type === 'mention');
    }
  },
  methods: {
    async loadNotifications() {
      const resp = await warpnetService.getNotifications(true);
      if (!resp || !resp.notifications || resp.notifications.length === 0) {
        this.notifications = [];
        return;
      }

      // Enrich notifications with actor profile data
      this.notifications = await Promise.all(
        resp.notifications.map(async (notification) => {
          if (notification.actor_id) {
            try {
              const actorProfile = await warpnetService.getProfile(notification.actor_id);
              if (actorProfile) {
                notification.actor_username = actorProfile.username;
                notification.actor_avatar = await warpnetService.getImage({
                  userId: notification.actor_id, 
                  key: actorProfile.avatar_key
                });
              }
            } catch (err) {
              console.error('Failed to load actor profile:', err);
            }
          }
          return notification;
        })
      );
    },
    goToProfile(userId) {
      if (userId) {
        this.$router.push({
          name: "Profile",
          params: { id: userId },
        });
      }
    },
    goToTweet(notification) {
      // Navigate to the related tweet if available
      if (notification.tweet_id && notification.tweet_user_id) {
        this.$router.push({
          name: "Profile",
          params: { id: notification.tweet_user_id },
        });
      }
    },
    gotoHome() {
      this.$router.push({
        name: "Home",
      });
    },
    submit(m = this.mode) {
      this.mode = m;
      this.$router.replace({
        name: "Notifications",
        query: { m: m, hash: Date.now() },
      });
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);
    try {
      this.loading = true;
      this.profile = warpnetService.getOwnerProfile();
      await this.loadNotifications();
    } catch (err) {
      console.error('Failed to load notifications:', err);
    } finally {
      this.loading = false;
    }
  },
};
</script>
