<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="flex container h-screen w-full">
    <div class="flex container h-screen w-full">
      <SideNav />

      <div
        class="w-full md:w-2/3 lg:w-1/2 h-full overflow-y-scroll no-scrollbar"
        v-scroll:bottom="loadMore"
      >
        <div class="px-5 py-3 border-b border-lighter flex items-center">
          <button
            @click="gotoHome()"
            class="rounded-full md:pr-2 focus:outline-none hover:bg-lightblue"
          >
            <i class="fas fa-arrow-left text-blue"></i>
          </button>
          <div class="lg:block ml-4">
            <h1 class="text-xl font-bold">{{ profile.username || "Anonymous" }}</h1>
            <p v-if="!noUser" class="text-left text-sm leading-tight text-dark">
              {{ profile.tweets_count || 0}} Tweets
            </p>
          </div>
        </div>

        <!-- background image -->
        <div
          class="border-b border-lighter flex"
          style="height:200px; display:block"
        >
          <div v-if="profile.background_image" class="h-full max-h-full">
            <img
              :src="profile.background_image"
              class="h-full w-full object-cover"
              alt="Background image"
            />
          </div>
          <div
            v-if="!profile.background_image"
            class="bg-gray-400 h-full max-h-full"
          ></div>
        </div>

        <!-- profile details -->
        <div class="py-3 flex flex-col">
          <div class="px-3 flex flex-row justify-between">
            <img
              v-if="profile"
              :src="profile.avatar || 'default_profile.png'"
              class="w-24 h-24 md:w-32 md:h-32 rounded-full border-white"
              style="margin-top: -80px; border-width: 6px;"

            />

            <div v-if="isMySelf(profile.id) && profile">
              <button
                v-if="
                  profile.avatar === null ||
                  profile.avatar === 'default_profile.png'
                "
                @click="setUpProfile()"
                class="text-xs md:text-base md:ml-auto text-blue font-bold px-4 py-2 rounded-full border border-blue mb-2 hover:bg-lightblue"
              >
                Set up profile
              </button>
              <button
                v-if="
                  profile.avatar !== null &&
                  profile.avatar !== 'default_profile.png'
                "
                @click="editProfile()"
                class="text-xs md:text-base md:ml-auto text-blue font-bold px-4 py-2 rounded-full border border-blue mb-2 hover:bg-lightblue"
              >
                Edit profile
              </button>
            </div>

            <div v-if="!noUser && !isSelf && !loading">
              <button
                class="text-xs md:text-base md:ml-auto mr-1 md:mr-3 text-blue font-bold px-3 py-1 md:px-3 md:py-2 rounded-full border border-blue mb-2 hover:bg-lightblue"
              >
                <i class="fas fa-ellipsis-h"></i>
              </button>
              <button
                v-if="isFollower()"
                class="text-xs md:text-base md:ml-auto mr-1 md:mr-3 text-blue font-bold px-3 py-1 md:px-3 md:py-2 rounded-full border border-blue mb-2 hover:bg-lightblue"
              >
                <i @click="sendMessage()" class="fas fa-envelope"></i>
              </button>
              <button
                v-if="!isFollowed()"
                @click="follow()"
                class="text-xs md:text-base md:ml-auto text-blue font-bold px-2 py-1 md:px-4 md:py-2 rounded-full border border-blue mb-2 hover:bg-lightblue w-24 md:w-28"
              >
                Follow
              </button>
              <button
                v-if="isFollowed()"
                @mouseover="followingLabel = 'Unfollow'"
                @mouseleave="followingLabel = 'Following'"
                @click="unfollow()"
                class="text-xs md:text-base md:ml-auto mr-1 md:mr-3 text-white bg-blue font-bold px-3 py-1 md:px-3 md:py-2 rounded-full border mb-2 hover:bg-red-700 w-22 md:w-28"
              >
                {{ followingLabel }}
              </button>
            </div>
          </div>
          <div v-if="!noUser && !loading" class="px-3">
            <p class="font-bold text-xl">{{ profile.username || '...' }}</p>
            <p class="text-dark">
              @{{ profile.id || '' }}
              <span
                  v-if="profile.isOffline"
                  class="text-sm font-medium bg-red-900 py-1 px-1 mx-2 rounded text-white align-middle"
              >Offline</span>
              <span
                v-if="isFollower() && !isSelf"
                class="text-sm font-medium bg-gray-100 py-1 px-1 mx-2 rounded text-gray-500 align-middle"
              >Follows you</span>
            </p>
            <p class="my-2">{{ profile.bio || '' }}</p>
            <div class="flex flex-col md:flex-row mt-1 mb-2">
              <div v-if="profile.website" class="flex flex-row mr-4">
                <i
                  class="fas fa-link text-dark align-text-bottom pt-1 mr-2"
                ></i>
                <a
                  :href="profile.website"
                  target="_blank"
                  class="text-dark"
                >
                  {{ profile.website.replace(/^https?:\/\//, '') }}
                </a>
              </div>
              <div v-if="joinedDate()" class="flex flex-row mr-4">
                <i
                  class="far fa-calendar-alt text-dark align-text-bottom pt-1 mr-2"
                ></i>
                <p class="text-dark">Joined {{ joinedDate() }}</p>
              </div>
            </div>
            <div v-if="!noUser && !loading" class="flex flex-row mt-1">
              <button
                @click="goToFollowing()"
                class="mr-4 flex flex-row hover:underline"
              >
                <span class="font-bold">{{ profile.followees_count || 0 }}</span>
                <span class="text-dark whitespace-pre"> Following</span>
              </button>
              <button
                @click="goToFollowers()"
                class="flex flex-row hover:underline"
              >
                <span class="font-bold">{{ profile.followers_count || 0 }}</span>
                <span class="text-dark whitespace-pre"> Followers</span>
              </button>
            </div>
          </div>
          <div v-if="noUser" class="px-5">
            <p class="text-black text-lg">
              @{{ $route.params.id }}
            </p>
          </div>
          <div
            v-if="!noUser && !loading"
            class="flex flex-row justify-evenly mt-2"
          >
            <button
              class="flex-grow text-dark font-bold border-b-2 border-blue p-1 md:px-2 md:py-4 hover:bg-lightblue"
            >
              Tweets
            </button>
            <button
              class="cursor-not-allowed flex-grow text-dark font-bold border-b-2 p-1 md:px-2 md:py-4 hover:bg-lightblue"
            >
              Tweets & replies
            </button>
            <button
              class="cursor-not-allowed flex-grow text-dark font-bold border-b-2 p-1 md:px-2 md:py-4 hover:bg-lightblue"
            >
              Media
            </button>
            <button
              class="cursor-not-allowed flex-grow text-dark font-bold border-b-2 p-1 md:px-2 md:py-4 hover:bg-lightblue"
            >
              Likes
            </button>
          </div>
        </div>

        <!-- tweets -->
        <Loader :loading="loading" />
        <div
          v-if="!noUser && !loading && tweets.length === 0"
          class="flex flex-col items-center justify-center w-full pt-10"
        >
          <p class="font-bold text-lg">
            <span>{{ isSelf ? "You" : `${profile.username || "User"}` }}</span> haven't
            tweeted yet
          </p>
          <p class="text-sm text-dark">
            When
            <span>{{ isSelf ? "you post" : `${profile.username || "user"} posts` }}</span>
            a tweet, it'll show up here.
          </p>
          <button
            v-if="isSelf"
            class="text-white bg-blue rounded-full font-semibold mt-4 px-4 py-2 hover:bg-darkblue"
          >
            <p class="hidden lg:block">Tweet now</p>
            <i class="fas fa-plus lg:hidden"></i>
          </button>
        </div>
        <Tweets v-if="!noUser" :tweets="tweets" />
      </div>
      <div
        class="hidden md:block w-1/3 z-0 h-full border-l border-lighter px-6 py-2 overflow-y-scroll no-scrollbar relative"
      >
        <DefaultRightBar
            :profile="profile"
        />
      </div>

      <SetUpProfileOverlay
        v-if="showSetUpProfileModal"
        :showSetUpProfileModal="showSetUpProfileModal"
        @close="showSetUpProfileModal = false"
      />

      <EditProfileOverlay
        v-if="showEditProfileModal"
        :showEditProfileModal="showEditProfileModal"
        @close="showEditProfileModal = false"
      />
    </div>
  </div>
</template>

<script>
import moment from "moment";
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: "Profile",
  components: {
    SideNav: defineAsyncComponent(() => import('@/components/SideNav.vue')),
    DefaultRightBar: defineAsyncComponent(() => import('@/components/DefaultRightBar.vue')),
    SearchBar: defineAsyncComponent(() => import('@/components/SearchBar.vue')),
    Loader: defineAsyncComponent(() => import('@/components/Loader.vue')),
    EditProfileOverlay: defineAsyncComponent(() => import('@/components/EditProfileOverlay.vue')),
    SetUpProfileOverlay: defineAsyncComponent(() => import('@/components/SetUpProfileOverlay.vue')),
    Tweets: defineAsyncComponent(() => import('@/components/Tweets.vue')),
  },
  data() {
    return {
      showSetUpProfileModal: false,
      showEditProfileModal: false,
      isSelf: false,
      followingLabel: "Following",
      loading: true,
      noUser: false,
      ownerProfile: {},
      profile: {},
      tweets: [],
      users: [],
      followers: [],
      followings: [],
    };
  },
  methods: {
    isMySelf(profileId) {
      return profileId === this.ownerProfile.id;
    },
    joinedDate(createdAt) {
      return moment(createdAt).format("MMMM YYYY");
    },
    gotoHome() {
      this.$router.push({
        name: "Home",
      });
    },
    sendMessage() {
      this.$router.push({
        name: "Messages",
        params: {
          id: this.profile.id,
        },
      });
    },
    isFollower() {
      return warpnetService.isFollower(this.profile.id);
    },
    isFollowed() {
      return warpnetService.isFollowed(this.profile.id);
    },
    goToFollowing() {
      this.$router.push({
        name: "Following",
        params: {
          id: this.profile.id,
        },
      });
    },
    goToFollowers() {
      this.$router.push({
        name: "Followers",
        params: {
          id: this.profile.id,
        },
      });
    },
    setUpProfile() {
      this.showSetUpProfileModal = true;
    },
    editProfile() {
      this.showEditProfileModal = true;
    },
    async follow() {
      try {
        await warpnetService.followUser(this.profile.id);
      } catch (err) {
        console.error(`failed to follow [${this.profile.id}]`, err);
      }
    },
    async unfollow() {
      try {
        await warpnetService.unfollowUser(this.profile.id);
      } catch (err) {
        console.error(`failed to unfollow [${this.profile.id}]`, err);
      }
    },
    async loadMore() {
      const tweets = await warpnetService.getTweets({userId:this.profile.id, cursorReset:false});
      this.tweets = this.tweets.concat(tweets);
    },
    enableMastodonMode() {
      const html = document.documentElement;
      html.classList.add("mastodon");
      localStorage.setItem("theme", "mastodon");
    },
    disableMastodonMode() {
      const html = document.documentElement;
      if (html.classList.contains("mastodon")) {
        html.classList.remove("mastodon");
        localStorage.setItem("theme", "light");
      }
    }
  },
  async created() {
    console.log("loading component:", this.$options.name);
    try {
      this.loading = true;
      const profileId = this.$route.params.id;
      if (!profileId) {
        this.noUser = true;
        this.loading = false;
        return;
      }

      this.ownerProfile = warpnetService.getOwnerProfile();

      this.profile = await warpnetService.getProfile(profileId);
      if (!this.profile) {
        this.noUser = true;
        this.loading = false;
        return;
      }
      if (this.profile.network === "mastodon") {
        this.enableMastodonMode()
      } else {
        this.disableMastodonMode();
      }

      this.profile.background_image = await warpnetService.getImage(
          {userId:profileId, key:this.profile.background_image_key},
      );
      this.profile.avatar = await warpnetService.getImage(
          {userId:profileId, key:this.profile.avatar_key},
      )

      this.isSelf = this.isMySelf(profileId);

      [this.users, this.tweets, this.followers, this.followings] = await Promise.all([
        warpnetService.getUsers({profileId:profileId, cursorReset:true}),
        warpnetService.getTweets({userId:profileId, cursorReset:true}),
        warpnetService.getFollowers({userId:profileId, cursorReset: true}),
        warpnetService.getFollowees({userId:profileId, cursorReset: true})
      ]);
    } catch (err) {
      console.error('Failed to load profile:', err);
      this.noUser = true;
    } finally {
      this.loading = false;
    }
  },
};
</script>
