<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div class="flex w-full h-screen flex-col-reverse md:flex-row" v-escape="esc">
    <!-- left side -->
    <div class="flex w-full md:w-1/2 h-full bg-blue p-5 md:p-0">
      <div class="flex items-center justify-center w-full h-full">
        <div class="flex flex-col">
          <div class="flex items-center">
            <i class="fas fa-search text-white text-2xl mr-5"></i>
            <p class="text-white font-bold text-xl">Follow your interests.</p>
          </div>
          <div class="flex items-center mt-10">
            <i class="fas fa-user-friends text-white text-2xl mr-4"></i>
            <p class="text-white font-bold text-xl">
              Hear what people are talking about.
            </p>
          </div>
          <div class="flex items-center mt-10">
            <i class="fas fa-comment text-white text-2xl mr-5"></i>
            <p class="text-white font-bold text-xl">Join the conversation.</p>
          </div>
        </div>
      </div>
    </div>

    <!-- right side -->
    <div class="flex w-full md:w-1/2 h-full">
      <div class="flex items-center justify-center w-full h-full">
        <div class="w-full md:w-1/2 flex flex-col font-bold p-5 md:p-0">
          <p class="text-3xl mb-12">
            Dive deep into the Warp and see what happens...
          </p>
          <p>Join Warpnet today.</p>
          <button v-if="isFirstRun"
            @click.prevent="setSignUpStep('step1')"
            class="rounded-full bg-blue font-bold text-lg text-white mt-4 p-3 hover:bg-darkblue"
          >
            Sign up
          </button>
          <LogInComponent v-else></LogInComponent>
        </div>
      </div>
    </div>

    <!-- sign up modal -->
    <div
      v-if="showModal !== ''"
      class="fixed w-full h-full top-0 left-0 flex items-center justify-center"
    >
      <div
        class="absolute w-full h-full bg-gray-900 opacity-50"
        @click.prevent="setSignUpStep('')"
      ></div>

      <div
        class="modal-main bg-white w-11/12 max-w-md mx-auto rounded-lg z-50 overflow-y-auto max-h-full"
      >
        <div v-if="showModal === 'step1'">
          <div class="pl-1 pr-4 py-1 h-12">
            <button
              @click="setSignUpStep('step2')"
              class="rounded-full bg-blue font-bold text-white mt-2 p-1 pl-3 pr-3 relative right-0 float-right hover:bg-darkblue"
              :class="
                `${
                  !username
                    ? 'opacity-50 cursor-not-allowed'
                    : ''
                }`
              "
            >
              Next
            </button>
            <i
              class="flex justify-center fab text-blue text-2xl mt-2 mb-8"
            ></i>
          </div>
          <div class="pt-5 px-8">
            <div class="flex justify-between items-center pb-8">
              <p class="text-2xl font-bold">Create your account</p>
            </div>
            <div class="w-full bg-lightblue border-b-2 border-dark mb-8 p-2">
              <p class="text-dark">Username</p>
              <input
                v-model="username"
                class="w-full bg-lightblue text-lg"
                type="text"
              />
            </div>
          </div>
        </div>

        <div v-if="showModal === 'step2'">
          <div class="pl-1 pr-4 py-1 h-12">
            <button
              @click="setSignUpStep('step1')"
              class="absolute rounded-full p-2 pl-3 hover:bg-lightblue"
            >
              <i class="fas fa-arrow-left text-blue"></i>
            </button>
            <button
              v-if="userResponsibility && localStorageLoss && futureAds"
              @click="setSignUpStep('step3')"
              class="rounded-full bg-blue font-bold text-white mt-2 p-1 pl-3 pr-3 relative right-0 float-right hover:bg-darkblue"
            >
              Next
            </button>
            <i
              class="flex justify-center fab text-blue text-2xl mt-2 mb-8"
            ></i>
          </div>
          <div class="pt-5 px-8">
            <div class="flex justify-between items-center pb-8">
              <p class="text-2xl font-bold">Important information</p>
            </div>

            <div class="mt-5 mb-8">
              <p class="font-bold text-xl mb-1">User Responsibility</p>
              <div class="flex justify-between items-top">
                <p>
                  I acknowledge that I am solely responsible for the content I upload to WarpNet.
                </p>
                <input class="mt-1 ml-2 mr-2" type="checkbox" v-model="userResponsibility" />
              </div>
            </div>

            <div class="mt-5 mb-8">
              <p class="font-bold text-xl mb-1">Local Storage Disclaimer</p>
              <div class="flex justify-between items-top">
                <p>
                  I understand that all my data is stored locally on my device, and if I lose access to this device,
                  my WarpNet account will be permanently lost.
                </p>
                <input class="mt-1 ml-2 mr-2" type="checkbox" v-model="localStorageLoss" />
              </div>
            </div>

            <div class="mt-5 mb-5">
              <p class="font-bold text-xl mb-1">Future Advertising</p>
              <div class="flex justify-between items-top">
                <p>
                  I understand that WarpNet may introduce sponsored content or advertisements in the future.
                </p>
                <input class="mt-1 ml-2 mr-2" type="checkbox" v-model="futureAds" />
              </div>
            </div>
          </div>
        </div>

        <div v-if="showModal === 'step3'">
          <div class="pl-1 pr-4 py-1 h-12">
            <button
              @click="setSignUpStep('step2')"
              class="absolute rounded-full p-2 pl-3 hover:bg-lightblue"
            >
              <i class="fas fa-arrow-left text-blue"></i>
            </button>
            <button
              @click="setSignUpStep('step4')"
              class="rounded-full bg-blue font-bold text-white mt-2 p-1 pl-3 pr-3 relative right-0 float-right hover:bg-darkblue"
            >
              Next
            </button>
            <i
              class="flex justify-center fab text-blue text-2xl mt-2 mb-8"
            ></i>
          </div>
          <div class="pt-5 px-8">
            <div class="flex justify-between items-center pb-4">
              <p class="text-2xl font-bold">You'll need a password</p>
            </div>

            <div class="w-full bg-lightblue border-b-2 border-dark p-2">
              <p class="leading-tight text-dark">Password</p>
              <input
                v-model="password"
                class="w-full bg-lightblue text-lg"
                :type="`${revealPassword ? 'text' : 'password'}`"
              />
            </div>

            <button
              @click="revealPassword = !revealPassword"
              class="text-blue pl-2"
            >
              Reveal password
            </button>
          </div>
        </div>

        <div v-if="showModal === 'step4'">
          <div class="pl-1 pr-4 py-1 h-12">
            <button
              @click="setSignUpStep('step3')"
              class="absolute rounded-full p-2 pl-3 hover:bg-lightblue"
            >
              <i class="fas fa-arrow-left text-blue"></i>
            </button>
            <p class="flex items-start ml-12 p-2 text-xl font-extrabold">
              Step 4 of 5
            </p>
          </div>
          <div class="pt-5 px-8">
            <div class="flex justify-between items-center pb-8">
              <p class="text-2xl font-bold">Create your account</p>
            </div>

            <p>
              By signing up, you agree to our
              <a href="https://github.com/Warp-net/docs/blob/main/legal/T%26C.md" class="text-blue">Terms</a>,
              <a href="https://github.com/Warp-net/docs/blob/main/legal/PRIVACY-POLICY.md" class="text-blue">Privacy Policy</a> and
            </p>
            <button
              v-if="!isLoading"
              @click="signMeUp"
              class="w-full rounded-full mt-4 py-3 bg-blue text-white font-bold hover:bg-darkblue"
            >
              Sign up
            </button>
            <div v-else class="w-full rounded-full mt-4 py-3">
              <ProgressBar/>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import {connectClient} from "@/lib/client";
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";
export default {
  name: "Root",
  components: {
    ProgressBar: defineAsyncComponent(() => import('@/components/ProgressBar.vue')),
    LogInComponent: defineAsyncComponent(() => import('@/components/LogInComponent.vue')),
  },
  data() {
    return {
      username: "",
      password: "",
      revealPassword: false,
      isFirstRun: false,
      isLoading: false,
      showModal: "",

      userResponsibility: false,
      futureAds: false,
      localStorageLoss: false,
    };
  },
  mounted() {
    this.isFirstRun = window.isFirstRun || false;
    console.log("Is first run:", this.isFirstRun);
    connectClient();
  },
  methods: {
    async signMeUp() {
      try {
        this.isLoading = true;
        await warpnetService.signInUser({
          username: this.username,
          password: this.password,
        });
        await this.setStep("step5");
      } catch (error) {
        alert(error);
        console.error("error signing up:", error);
      } finally {
        this.isLoading = false;
        this.$router.push({ name: "Home" });
      }
    },
    async setStep(step) {
      this.showModal = step || ""
    },
    setSignUpStep(step) {
      switch (step) {
        case "step2":
          if (!this.username) {
            return;
          }
          break;
        case "step4":
          break;
      }
      this.setStep(step);
    },
    esc() {
      this.setStep("");
      this.isLoading = false;
    },
  },
};
</script>
