<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div
    class="fixed w-full h-full top-0 left-0 flex items-center justify-center"
  >
    <div
      class="absolute w-full h-full bg-gray-900 opacity-50"
      @click.prevent="this.$emit('close')"
    ></div>

    <div
      class="modal-main bg-white mx-auto rounded-lg z-50 overflow-y-auto no-scrollbar"
      style="height:85%; width:40%"
    >
      <div class="pl-1 pr-4 py-1 h-16 border-b-2 border-lightblue">
        <button
          @click="saveProfile"
          class="rounded-full bg-blue font-bold text-white mt-2 p-1 px-4 relative right-0 float-right focus:outline-none hover:bg-darkblue"
        >
          Save
        </button>
        <div class="flex flex-row mt-1 ml-4">
          <i
            @click="this.$emit('close')"
            class="fas fa-times text-blue text-2xl mb-8 mr-6 rounded-full bg-white p-2 px-3 hover:bg-lightblue cursor-pointer"
          ></i>
          <p class="text-xl pt-1 font-bold">Edit profile</p>
        </div>
      </div>

      <div class="border-l-2 border-r-2 border-white">
        <!-- background image -->
        <div class="relative" style="height:200px; display:block">
          <!-- change background overlay -->
          <div
            class="absolute w-full max-w-full h-full max-h-full bg-gray-600 opacity-50"
          ></div>
          <button
            @click="openFileInput('backgroundFileInput')"
            class="absolute hover:bg-gray-800 p-3 rounded-full"
            style="margin-left: 45%; margin-top: 80px"
          >
            <i class="text-2xl fas fa-camera text-white"></i>
            <input
              @change="fileChange('backgroundFileInput', 'background_image')"
              ref="backgroundFileInput"
              accept="image/*"
              type="file"
              class="hidden"
            />
          </button>

          <div v-if="background_image" class="h-full max-h-full">
            <img :src="background_image" class="h-full w-full object-cover" alt="Background" />
          </div>
          <div
            v-if="!background_image"
            class="bg-gray-400 h-full max-h-full"
          ></div>
        </div>

        <div class="p-3 flex flex-col">
          <!-- profile image -->
          <div
            style="margin-top:-80px"
            class="relative w-32 h-32 rounded-full mb-6"
          >
            <div
              class="absolute w-32 h-32 rounded-full bg-gray-600 opacity-50 border-4 border-white"
            ></div>
            <button
              @click="openFileInput('imageUrlFileInput')"
              class="absolute hover:bg-gray-800 p-3 rounded-full ml-10 mt-10"
            >
              <i class="text-2xl fas fa-camera text-white"></i>
              <input
                @change="fileChange('imageUrlFileInput', 'avatar')"
                ref="imageUrlFileInput"
                accept="image/*"
                type="file"
                class="hidden"
              />
            </button>

            <img
              :src="avatar"
              class="w-32 h-32 rounded-full border-4 border-white"
              alt="Avatar"
            />
          </div>

          <div class="w-full bg-lightest border-b-2 border-dark mb-6 py-1 px-3">
            <label class="text-dark" for="username">Name</label>
            <input
              id="username"
              v-model.trim="username"
              class="w-full bg-lightest text-lg focus:outline-none"
              type="text"
              required
            />
          </div>
          <div class="w-full bg-lightest border-b-2 border-dark mb-6 py-1 px-3">
            <label class="text-dark" for="bio">Bio</label>
            <textarea
              id="bio"
              v-model.trim="bio"
              class="w-full bg-lightest text-lg focus:outline-none"
              placeholder="Add your bio"
            />
          </div>
          <div class="w-full bg-lightest border-b-2 border-dark mb-6 py-1 px-3">
            <label class="text-dark" for="website">Website</label>
            <input
              id="website"
              v-model.trim="website"
              class="w-full bg-lightest text-lg focus:outline-none"
              type="url"
              placeholder="Add your website"
            />
          </div>
          <div
            class="w-full bg-lightest border-b-2 border-dark mb-24 py-1 px-3"
          >
            <label class="text-dark" for="birthdate">Birth date</label>
            <input
              id="birthdate"
              v-model="birthdate"
              class="w-full bg-lightest text-lg focus:outline-none"
              type="date"
              placeholder="Add your birth date"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<style scoped>
.modal-main {
  max-height: 90vh;
}

input[type="date"]::-webkit-calendar-picker-indicator {
  cursor: pointer;
}

textarea {
  resize: none;
}
</style>


<script>
import moment from "moment";
import {warpnetService} from "@/service/service";

export default {
  name: "EditProfileOverlay", 
  props: {
    showEditProfileModal: Boolean 
  },
  data() {
    return {
      profile: {},
      username: undefined,
      background_image: undefined,
      avatar: undefined,
      bio: undefined,
      website: undefined,
      birthdate: undefined,
    };
  },
  methods: {
    handleKeyup(event) {
      if (event.key === "Escape") {
        this.$emit("close");
      }
    },
    openFileInput(ref) {
      this.$refs[ref].click();
    },
    async fileChange(ref, prop) {
      const file = this.$refs[ref].files[0];
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => this[prop] = reader.result;
      reader.onerror = (error) => alert(error);
    },
    async saveProfile() {
      const p = {
        username: this.username,
        avatar_key: "",
        background_image_key: "",
        bio: this.bio,
        website: this.website,
        birthdate: this.birthdate ? moment(this.birthdate, "YYYY-MM-DD").format("YYYY-MM-DD") : null,
      };
      p.avatar_key = await warpnetService.uploadImage(this.avatar)
      p.background_image_key = await warpnetService.uploadImage(this.background_image)

      this.profile = await warpnetService.editMyProfile(p);

      this.background_image = await warpnetService.getImage({userId:this.profile.id, key:this.profile.background_image_key});
      this.avatar = await warpnetService.getImage({userId:this.profile.id, key:this.profile.avatar_key})

      this.$emit("close");
    },
  },
  mounted() {
    window.addEventListener("keyup", this.handleKeyup);
  },
  beforeUnmount() {
    window.removeEventListener("keyup", this.handleKeyup);
  },
  async created() {
    console.log("loading component:", this.$options.name);
    console.log(this.$options.name);
    this.profile = warpnetService.getOwnerProfile();
    this.username = this.profile.username;
    this.background_image = await warpnetService.getImage({userId:this.profile.id, key:this.profile.background_image_key});
    this.avatar = await warpnetService.getImage({userId:this.profile.id, key:this.profile.avatar_key})
    this.bio = this.profile.bio;
    this.website = this.profile.website;
    this.birthdate = this.profile.birthdate;
  },
};
</script>
