<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
    <div class="w-full bg-lightblue border-b-2 border-dark mt-20 mb-10 p-2 input_field">
      <p class="text-dark text-center">Username</p>
      <input
          v-model="username"
          class="w-full bg-lightblue text-lg text-center"
          type="text"
          ref="username"
          @keydown.enter="$refs.password.focus()"
      />
    </div>
    <div class="w-full bg-lightblue border-b-2 border-dark mt-10 mb-10 p-2 input_field">
      <p class="text-dark text-center">Password</p>
      <input
          v-model="password"
          class="w-full bg-lightblue text-lg text-center"
          type="password"
          ref="password"
          @keydown.enter="signIn"
      />
    </div>
    <div class="flex justify-center">
      <button
        v-if="!isLoading"
        @click.prevent="signIn"
        class="w-full md:w-1/3 font-bold rounded-full bg-blue text-white p-3 hover:bg-darkblue"
      >
        Log in
      </button>
      <div v-else class="w-full rounded-full mt-4 py-3">
        <ProgressBar/>
      </div>
    </div>
    <div v-if="showErrorModal" class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 z-50">
      <div class="bg-white rounded-xl p-6 w-80 shadow-lg text-center">
        <p class="text-lg font-bold bg-blue mb-4">{{ errorMessage }}</p>
        <div class="flex space-x-4">
          <button
              @click="handleLogout"
              class="flex-1 bg-blue text-white font-bold py-2 px-4 rounded"
          >
            Logout
          </button>

        </div>
      </div>
    </div>
  </template>
  
<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";
export default {
  name: "LogInComponent",
  components: {
    ProgressBar: defineAsyncComponent(() => import('./ProgressBar.vue'))
  },
  data() {
    return {
      username: "",
      password: "",
      isLoading: false,
      showErrorModal: false,
      errorMessage: "",
    };
  },
  created: function () {
    this.$nextTick(() => this.$refs.username.focus());
  },
  methods: {
    async signIn() {
      this.isLoading = true;
      try {
        await warpnetService.signInUser({username: this.username, password: this.password});
      } catch (error) {
        alert(error)
        console.log("error signing in", error);
        this.errorMessage = error?.message || "Unknown error during sign-in.";
        this.showErrorModal = true;
      } finally {
        this.isLoading = false;
        this.$router.push({ name: "Home" });
      }
    },
    async handleLogout() {
      try {
        await warpnetService.logoutUser();
        console.log("User has been logged out");
      } catch (error) {
        console.error("Error logging out", error);
      } finally {
        this.showErrorModal = false;
      }
    },
  },
};
</script>

<style scoped>
  .input_field {
    border-radius: 20px;
  }
  input:-webkit-autofill {
    background-color: #f4d5e1 !important;
    -webkit-box-shadow: 0 0 0px 1000px #f4d5e1 inset !important;
    border-radius: 8px;
  }
</style>
  