<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
    <div
      v-if="show"
      class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 z-50"
      @click.self="close"
    >
      <div class="bg-white rounded-lg shadow-lg p-6 w-80 relative">
        <button
          class="absolute top-2 right-2 text-gray-500 hover:text-gray-700"
          @click="close"
        >
          <i class="fas fa-times"></i>
        </button>
        
        <h3 class="text-xl font-semibold text-center mb-4">Your QR Code</h3>
        
        <div v-if="qrData" class="flex justify-center mb-4">
          <img :src="qrData" alt="QR Code" class="w-48 h-48" />
        </div>
        
        <div v-else class="text-center text-gray-500">
          <p>No QR code is currently available. Please try again later.</p>
        </div>
  
        <p class="text-sm text-gray-600 text-center">
          Scan this QR code with your app to log in.
        </p>
      </div>
    </div>
  </template>
  
  <script>

  export default {
    props: {
      show: {
        type: Boolean,
        required: true,
      },
      qrData: {
        type: String,
        required: false,
      },
    },
    emits: ["close"],
    methods: {
      close() {
        this.$emit("close");
      },
      handleEscape(event) {
        if (event.key === "Escape") {
          this.close();
        }
      },
    },
    mounted() {
      window.addEventListener("keydown", this.handleEscape);
    },
    beforeUnmount() {
      window.removeEventListener("keydown", this.handleEscape);
    },
  };
  </script>
  
  <style scoped>
  </style>