<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div
    v-if="showReplyOverlay"
    class="fixed w-full h-full z-10 top-0 left-0 flex items-center justify-center"
  >
    <div
      class="absolute w-full h-full bg-gray-900 opacity-50"
      @click="this.$emit('close')"
    ></div>

    <div
      class="modal-main bg-white mx-auto rounded-lg z-0 overflow-y-auto"
      style="width:40%"
    >
      <div class="pl-1 pr-4 py-1 h-16 border-b-2 border-lightblue">
        <div class="flex flex-row mt-1 ml-4">
          <i
            @click="this.$emit('close')"
            class="fas fa-times text-blue text-2xl mb-8 mr-6 rounded-full bg-white p-2 px-3 hover:bg-lightblue cursor-pointer"
          ></i>
        </div>
      </div>

      <div
        v-if="profile"
        class="border-l-2 border-r-2 border-white flex flex-col"
      >
        <!-- Original TweetBlock -->
        <div class="p-3 flex flex-row">
          <div class="flex-none mr-4">
            <img
              :src="`${profile.avatar || 'default_profile.png'}`"
              class="h-12 w-12 rounded-full flex-none"

            />
          </div>

          <div class="w-full">
            <div class="flex items-center w-full">
              <p class="font-semibold">{{ tweet.user_id }}</p>
              <p class="text-sm text-dark ml-2">
                @{{ tweet.username }}
              </p>
              <p class="text-sm text-dark ml-2">·</p>
              <p class="text-sm text-dark ml-2">
                {{ $filters.timeago(tweet.created_at) }}
              </p>
            </div>
            <p class="py-2" v-linkify>
              {{ tweet.text }}
            </p>
          </div>
        </div>

        <!-- ReplyBlock -->
        <div v-if="profile.network === 'warpnet'" class="p-3 flex flex-row">
          <div class="flex-none mr-4">
            <img
              :src="`${profile.avatar || 'default_profile.png'}`"
              class="h-12 w-12 rounded-full flex-none"
              alt="User avatar"
            />
          </div>

          <div class="w-full mb-2">
            <form @submit.prevent="sendReply" class="w-full relative">
              <textarea
                v-model="text"
                placeholder="Tweet your reply"
                class="w-full focus:outline-none mt-3 pb-3"
              ></textarea>
              <div>
                <i class="text-lg text-blue mr-4 far fa-image cursor-pointer"></i>
                <i class="text-lg text-blue mr-4 fas fa-film cursor-not-allowed"></i>
                <i class="text-lg text-blue mr-4 far fa-chart-bar cursor-not-allowed"></i>
                <i class="text-lg text-blue mr-4 far fa-smile cursor-not-allowed"></i>
              </div>
              <button
                type="submit"
                class="h-10 px-4 text-white font-semibold bg-blue hover:bg-darkblue rounded-full absolute bottom-0 right-0"
                :class="{'opacity-50 cursor-not-allowed': !text}"
                :disabled="!text"
              >
                Reply
              </button>
            </form>
          </div>
        </div>
        <div>
          <Tweets :tweets="replies" />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: "ReplyOverlay",
  components: {
    Tweets: defineAsyncComponent(() => import('@/components/Tweets.vue'))
  },
  props: ["tweet", "showReplyOverlay", "profile"],
  data() {
    return {
      text: "",
      replies: [],
    };
  },
  methods: {
    async sendReply() {
      await warpnetService.replyTweet({
        rootId: this.tweet.root_id || this.tweet.id,
        parentId: this.tweet.id,
        parentUserId: this.tweet.user_id,
        text: this.text
      });
      this.$emit('close');
    },
  },
  beforeUnmount() {
    window.removeEventListener("keydown", this.handleEscape);
  },
  async created() {
    console.log("loading component:", this.$options.name);
    const repliesRequest = {
      rootId: this.tweet.root_id || this.tweet.id,
      parentId: this.tweet.id,
    }
    let replies = await warpnetService.getReplies(repliesRequest, true);
    for (const node of replies || []) {
      this.replies.push(node.reply);
    }
  },
};
</script>
