<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div>
    <QRCodeModal
      :show="qrModalOpen"
      :qrData="qrCode"
      @close="closeQR"
    />
  </div>

  <!-- Mobile bottom tab bar (visible below sm breakpoint, <360px per tailwind.config.js) -->
  <nav class="fixed bottom-0 left-0 right-0 z-50 bg-white border-t border-lighter flex justify-around items-center py-2 sm:hidden" role="navigation" aria-label="Mobile navigation">
    <button @click="open('Home')" :class="$route.name === 'Home' ? 'text-blue' : 'text-dark'" class="flex flex-col items-center p-2 flat-btn" aria-label="Home">
      <i class="fa fa-home text-xl" aria-hidden="true"></i>
      <span class="text-xs mt-0.5">Home</span>
    </button>
    <button @click="open('Notifications')" :class="$route.name === 'Notifications' ? 'text-blue' : 'text-dark'" class="flex flex-col items-center p-2 relative flat-btn" aria-label="Notifications">
      <i class="fa-bell text-xl" :class="$route.name === 'Notifications' ? 'fas' : 'far'" aria-hidden="true"></i>
      <span v-if="newNotifications > 0" class="absolute -top-0.5 right-0 inline-flex items-center justify-center w-4 h-4 rounded-full text-[10px] font-bold bg-blue text-white">{{ newNotifications }}</span>
      <span class="text-xs mt-0.5">Alerts</span>
    </button>
    <button @click="open('Chats')" :class="$route.name === 'Chats' || $route.name === 'Messages' ? 'text-blue' : 'text-dark'" class="flex flex-col items-center p-2 relative flat-btn" aria-label="Messages">
      <i class="fa-envelope text-xl" :class="$route.name === 'Chats' || $route.name === 'Messages' ? 'fas' : 'far'" aria-hidden="true"></i>
      <span v-if="newMessages > 0" class="absolute -top-0.5 right-0 inline-flex items-center justify-center w-4 h-4 rounded-full text-[10px] font-bold bg-blue text-white">{{ newMessages }}</span>
      <span class="text-xs mt-0.5">Chats</span>
    </button>
    <button @click="open('Profile')" :class="$route.name === 'Profile' ? 'text-blue' : 'text-dark'" class="flex flex-col items-center p-2 flat-btn" aria-label="Profile">
      <i class="fa-user text-xl" :class="$route.name === 'Profile' ? 'fas' : 'far'" aria-hidden="true"></i>
      <span class="text-xs mt-0.5">Profile</span>
    </button>
  </nav>

  <nav
    class="w-1/6 md:w-1/12 xl:w-1/6 border-r border-lighter lg:px-6 py-2 flex-col justify-between hidden sm:flex"
    role="navigation"
    aria-label="Main navigation"
  >
    <div>
      <button
        class="h-12 w-12 hover:bg-lightblue text-3xl text-blue rounded-full"
      >
      </button>
      <div>
        <button
          @click="open('Home')"
          class="hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1"
          aria-label="Home"
        >
          <i
            class="fa fa-home"
            :class="$route.name === 'Home' ? 'text-2xl' : 'text-xl'"
            aria-hidden="true"
          ></i>
          <p
            class="text-lg ml-4 text-left hidden xl:block"
            :class="$route.name === 'Home' ? 'font-bold' : ''"
          >
            Home
          </p>
        </button>
<!--        <button-->
<!--          class="focus:outline-none hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1"-->
<!--        >-->
<!--          <i class="fas fa-hashtag" aria-hidden="true"></i>-->
<!--          <p class="text-lg ml-4 text-left hidden xl:block">Explore</p>-->
<!--        </button>-->
        <button
          @click="open('Notifications')"
          class="relative hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1"
          aria-label="Notifications"
        >
          <i
            class="fa-bell"
            :class="
              $route.name === 'Notifications' ? 'text-2xl fas' : 'text-xl far'
            "
            aria-hidden="true"
          ></i>
          <span v-if="newNotifications > 0" class="absolute -mt-6 ml-2">
            <div
              class="inline-flex items-center px-1.5 py-0.5 border-2 border-white rounded-full text-xs font-semibold leading-4 bg-blue text-white"
            >
              {{ newNotifications }}
            </div>
          </span>
          <p
            class="text-lg ml-4 text-left hidden xl:block"
            :class="$route.name === 'Notifications' ? 'font-bold' : ''"
          >
            Notifications
          </p>
        </button>
        <button
          @click="open('Chats')"
          class="hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1"
          aria-label="Messages"
        >
          <i
            class="fa-envelope"
            :class="$route.name === 'Chats' ? 'text-2xl fas' : 'text-xl far'"
            aria-hidden="true"
          ></i>
          <span v-if="newMessages > 0" class="absolute -mt-6 ml-2">
            <div
              class="inline-flex items-center px-1.5 py-0.5 border-2 border-white rounded-full text-xs font-semibold leading-4 bg-blue text-white"
            >
              {{ newMessages }}
            </div>
          </span>
          <p
            class="text-lg ml-4 text-left hidden xl:block"
            :class="$route.name === 'Chats' ? 'font-bold' : ''"
          >
            Messages
          </p>
        </button>
        <button
          disabled
          class="hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1 opacity-50 cursor-not-allowed"
          aria-label="Bookmarks (coming soon)"
          title="Coming soon"
        >
          <i class="text-xl far fa-bookmark" aria-hidden="true"></i>
          <p class="text-lg ml-4 text-left hidden xl:block">Bookmarks</p>
        </button>
<!--        <button-->
<!--          class="focus:outline-none hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1"-->
<!--        >-->
<!--          <i class="text-xl fas fa-clipboard-list" aria-hidden="true"></i>-->
<!--          <p class="text-lg ml-4 text-left hidden xl:block">Lists</p>-->
<!--        </button>-->
        <button
          @click="open('Profile')"
          class="hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1"
          aria-label="Profile"
        >
          <i
            class="fa-user"
            :class="$route.name === 'Profile' ? 'text-2xl fas' : 'text-xl far'"
            aria-hidden="true"
          ></i>
          <p
            class="text-lg ml-4 text-left hidden xl:block"
            :class="$route.name === 'Profile' ? 'font-bold' : ''"
          >
            Profile
          </p>
        </button>
        <button
          disabled
          class="hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1 opacity-50 cursor-not-allowed"
          aria-label="Settings (coming soon)"
          title="Coming soon"
        >
          <i class="text-xl fas fa-cog" aria-hidden="true"></i>
          <p class="text-lg ml-4 text-left hidden xl:block">Settings</p>
        </button>
      </div>

      <button
        @click="open('Home')"
        class="text-white bg-blue rounded-full font-semibold h-12 lg:h-auto w-12 xl:w-full hover:bg-darkblue p-3"
      >
        <p class="hidden xl:block">Tweet</p>
        <i class="fas fa-plus xl:hidden"></i>
      </button>
    </div>
    <div v-if="profile" class="xl:w-full relative mt-2 w-10 h-10">
      <button
        @click="dropdown = !dropdown"
        class="flex items-center w-full hover:bg-lightblue rounded-full"
      >
        <img
          :src="profile.avatar || '/default_profile.png'"
          class="w-10 h-10 rounded-full object-cover bg-transparent"
        />
        <div class="hidden xl:block ml-4 truncate">
          <div class="text-left text-sm font-bold leading-tight truncate">
            {{ profile.username }}
          </div>
          <div class="text-left text-sm leading-tight text-dark truncate">
            {{ profile.user_id }}
          </div>
        </div>
        <i class="hidden xl:block fas fa-angle-down ml-auto text-lg"></i>
      </button>
      <div
        v-if="dropdown"
        class="absolute bottom-0 left-0 w-80 rounded-lg shadow-md border-lightest bg-white mb-16"
      >
        <button
          @click="dropdown = false"
          class="p-3 flex items-center w-full hover:bg-lightest"
        >
          <img
            :src="profile.avatar || '/default_profile.png'"
            class="w-10 h-10 rounded-full object-cover bg-transparent"
          />
          <div class="ml-4">
            <p class="text-left text-sm font-bold leading-tight">
              {{ profile.username }}
            </p>
            <p class="text-left text-sm leading-tight text-dark">
              {{ profile.user_id }}
            </p>
          </div>
          <i class="fas fa-check ml-auto text-blue"></i>
        </button>
        <button
          class="w-full text-left hover:bg-lightest border-t border-lighter p-3 text-sm"
          @click="toggleDarkMode"
        >
          Toggle Theme
        </button>
        <button
          @click="signInByQR"
          class="w-full text-left hover:bg-lightest border-t border-lighter p-3 text-sm"
        >
          Sign in by QR-code
        </button>
      </div>
    </div>
  </nav>
</template>

<script>
import QRCodeModal from "@/components/QRCodeModal.vue";
import {warpnetService} from "@/service/service";

export default {
  name: "SideNav",
  components: {
    QRCodeModal,
  },
  data() {
    return {
      dropdown: false,
      profile: {},
      newMessages: 0,
      newNotifications: 0,
      qrModalOpen: false,
      qrCode: "",
      unsubscribeNotifications: null,
    };
  },
  mounted() {
    const theme = localStorage.getItem("theme");
    if (theme === "dark" || (!theme && window.matchMedia("(prefers-color-scheme: dark)").matches)) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  },
  methods: {
    async open(target) {
      const current = this.$route.name;
      if (
        target !== current ||
        this.$route.params.id !== this.profile.user_id
      ) {
        this.$router.push({
          name: target,
          params: {
            id: this.profile.user_id,
          },
        });
      }
    },
    toggleDarkMode() {
      const html = document.documentElement;
      if (html.classList.contains("dark")) {
        html.classList.remove("dark");
        localStorage.setItem("theme", "light");
      } else {
        html.classList.add("dark");
        localStorage.setItem("theme", "dark");
      }
    },
    async signInByQR() {
        this.qrCode = await warpnetService.getQR()
        this.qrModalOpen = true
    },
    async closeQR() {
      this.qrModalOpen = false
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);
    this.profile = warpnetService.getOwnerProfile();

    this.profile.avatar = await warpnetService.getImage({userId:this.profile.user_id, key:this.profile.avatar_key})

    this.unsubscribeNotifications = warpnetService.subscribeNotifications((resp) => {
      this.newNotifications = resp.unread_count || 0;
    });

    const resp = await warpnetService.getNotifications(true)
    if (resp) {
      this.newNotifications = resp.unread_count;
    }
  },
  beforeUnmount() {
    if (this.unsubscribeNotifications) {
      this.unsubscribeNotifications();
      this.unsubscribeNotifications = null;
    }
  },
};
</script>
