<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div v-if="tweet.retweeted_by && tweet.retweeted_by !== ''">
    <!-- Retweet header -->
    <div class="pt-4 pl-4 flex flex-row">
      <div class="w-12 mr-4 flex justify-end">
        <i class="text-sm pt-1 fas fa-retweet text-dark"></i>
      </div>
      <p class="text-sm text-dark">{{ label }}</p>
    </div>
  </div>
  <div
      class="w-full p-2 pt-1 pb-1 md:p-4 md:pt-2 md:pb-2 border-b hover:bg-lightest flex"
  >
    <div class="flex-none mr-2 md:mr-4 pt-1">
      <a>
        <img
          :src="`${this.profile.avatar || '/default_profile.png'}`"
          class="h-12 w-12 rounded-full flex-none"
        />
      </a>
    </div>
    <div class="w-full">
      <div class="flex items-center w-full">
        <a @click="gotoProfile(tweet.user_id)">
          <p class="font-semibold" >{{ tweet.username || 'Anonymous' }}</p>
        </a>
        <p class="hidden md:block text-sm text-dark ml-2">
          @{{ tweet.user_id }}
        </p>
        <p class="text-sm text-dark ml-2">·</p>
        <p class="text-sm text-dark ml-2">{{ $filters.timeago(tweet.created_at) }}</p>
        <div class="relative ml-auto">
          <i @click="toggleDropdown" class="fas fa-ellipsis-h text-sm text-dark cursor-pointer hover:text-blue p-2 rounded-full hover:bg-lightblue"></i>
          <div v-if="showDropdown" class="absolute right-0 mt-2 w-56 bg-white dark:bg-gray-800 rounded-lg shadow-xl border border-lighter z-50">
            <button 
              v-if="isOwnTweet" 
              @click="pinTweet" 
              class="w-full text-left px-4 py-3 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center"
            >
              <i class="fas fa-thumbtack mr-3 text-blue w-4"></i>
              <span>{{ tweet.pinned ? 'Unpin from profile' : 'Pin to profile' }}</span>
            </button>
            
            <button 
              @click="copyLink" 
              class="w-full text-left px-4 py-3 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center"
            >
              <i class="fas fa-link mr-3 text-blue w-4"></i>
              <span>Copy link to Tweet</span>
            </button>
            
            <button 
              @click="embedTweet" 
              class="w-full text-left px-4 py-3 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center"
            >
              <i class="fas fa-code mr-3 text-blue w-4"></i>
              <span>Embed Tweet</span>
            </button>
            
            <div class="border-t border-lighter"></div>
            
            <button 
              v-if="!isOwnTweet"
              @click="muteConversation" 
              class="w-full text-left px-4 py-3 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center"
            >
              <i class="fas fa-volume-mute mr-3 text-dark w-4"></i>
              <span>Mute this conversation</span>
            </button>
            
            <button 
              v-if="!isOwnTweet"
              @click="notInterested" 
              class="w-full text-left px-4 py-3 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center"
            >
              <i class="fas fa-ban mr-3 text-dark w-4"></i>
              <span>Not interested in this Tweet</span>
            </button>
            
            <div v-if="!isOwnTweet" class="border-t border-lighter"></div>
            
            <button 
              v-if="!isOwnTweet"
              @click="blockUser" 
              class="w-full text-left px-4 py-3 text-sm text-red-600 hover:bg-red-50 dark:hover:bg-red-900 flex items-center"
            >
              <i class="fas fa-user-slash mr-3 w-4"></i>
              <span>Block @{{ tweet.user_id }}</span>
            </button>
            
            <button 
              v-if="!isOwnTweet"
              @click="reportTweet" 
              class="w-full text-left px-4 py-3 text-sm text-red-600 hover:bg-red-50 dark:hover:bg-red-900 flex items-center"
            >
              <i class="fas fa-flag mr-3 w-4"></i>
              <span>Report Tweet</span>
            </button>
            
            <div v-if="isOwnTweet" class="border-t border-lighter"></div>
            
            <button 
              v-if="isOwnTweet"
              @click="deleteTweet" 
              class="w-full text-left px-4 py-3 text-sm text-red-600 hover:bg-red-50 dark:hover:bg-red-900 flex items-center rounded-b-lg"
            >
              <i class="fas fa-trash mr-3 w-4"></i>
              <span>Delete Tweet</span>
            </button>
          </div>
        </div>
      </div>
      <p v-if="!tweet.moderation || tweet.moderation?.is_ok" class="pb-2">
        {{ tweet.text }} 
      </p>
      <p v-else class="pb-2 bg-red-300">
        Moderated: {{ tweet.moderation.reason }}.
      </p>
      <div v-if="tweet.image" class="mt-2">
        <img
            :src="tweet.image"
            alt="Tweet image"
            class="rounded-lg max-w-full border border-lighter"
        />
      </div>
      <div class="flex w-full">
        <div class="flex items-center text-sm text-dark w-1/4">
          <button
            @click="replyToTweet"
            class="mr-2 rounded-full hover:bg-lighter"
          >
            <i class="far fa-comment"></i>
          </button>
          <p v-if="getRepliesCount(tweet.id) > 0">{{ getRepliesCount(tweet.id) || '?' }}</p>
        </div>
        <div class="flex items-center text-sm text-dark w-1/4">
          <button
            @click="retweet()"
            class="mr-2 rounded-full hover:bg-lighter"
          >
            <i
              :class="
                `fas fa-retweet ${tweet.retweeted_by ? 'text-green-500' : ''}`
              "
            ></i>
          </button>
          <p v-if="getRetweetsCount(tweet.id) > 0">{{ getRetweetsCount(tweet.id) || '?'}}</p>
        </div>
        <div class="flex items-center text-sm text-dark w-1/4">
          <button
            @click="like()"
            class="mr-2 rounded-full hover:bg-lighter"
          >
            <i :class="`fas fa-heart ${getLikesCount(tweet.id) > 0 ? 'text-red-600' : ''}`"></i>
          </button>
          <p v-if="getLikesCount(tweet.id) > 0">{{ getLikesCount(tweet.id) }}</p>
        </div>
        <div class="flex items-center text-sm text-dark w-1/4">
          <i class="fas fa-share-square mr-3 cursor-not-allowed"></i>
        </div>
      </div>
    </div>
    <ReplyOverlay
        v-if="showReplyOverlay"
        :tweet="tweet" :profile="profile"
        :showReplyOverlay="showReplyOverlay"
        @close="showReplyOverlay = false"
    />
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: "Tweet",
  props: ["tweet"],
  components: {
    ReplyOverlay: defineAsyncComponent(() => import('./ReplyOverlay.vue'))
  },
  data() {
    return {
      profile: {},
      showReplyOverlay: false,
      showDropdown: false,
      label: "You Retweeted",
      likesCount: new Map(),
      retweetsCount: new Map(),
      repliesCount: new Map(),
    };
  },
  computed: {
    isOwnTweet() {
      const ownerProfile = warpnetService.getOwnerProfile();
      return ownerProfile && this.tweet.user_id === ownerProfile.user_id;
    }
  },
  methods: {
    toggleDropdown() {
      this.showDropdown = !this.showDropdown;
    },
    copyLink() {
      const tweetUrl = `${window.location.origin}/#/tweet/${this.tweet.user_id}/${this.tweet.id}`;
      navigator.clipboard.writeText(tweetUrl).then(() => {
        alert('Link copied to clipboard!');
        this.showDropdown = false;
      }).catch(err => {
        console.error('Failed to copy link:', err);
        alert('Failed to copy link');
      });
    },
    pinTweet() {
      // TODO: Implement pin/unpin functionality when backend API is available
      console.log('Pin tweet:', this.tweet.id);
      alert(this.tweet.pinned ? 'Tweet unpinned from profile' : 'Tweet pinned to profile');
      this.showDropdown = false;
    },
    embedTweet() {
      const embedCode = `<blockquote class="warpnet-tweet">
  <p>${this.tweet.text}</p>
  <a href="${window.location.origin}/#/tweet/${this.tweet.user_id}/${this.tweet.id}">
    @${this.tweet.user_id}
  </a>
</blockquote>`;
      navigator.clipboard.writeText(embedCode).then(() => {
        alert('Embed code copied to clipboard!');
        this.showDropdown = false;
      }).catch(err => {
        console.error('Failed to copy embed code:', err);
        alert('Failed to copy embed code');
      });
    },
    muteConversation() {
      // TODO: Implement mute conversation when backend API is available
      console.log('Mute conversation for tweet:', this.tweet.id);
      alert('Conversation muted');
      this.showDropdown = false;
    },
    notInterested() {
      // TODO: Implement "not interested" functionality
      console.log('Not interested in tweet:', this.tweet.id);
      alert('Thanks for the feedback. You\'ll see fewer Tweets like this.');
      this.showDropdown = false;
    },
    blockUser() {
      if (confirm(`Are you sure you want to block @${this.tweet.user_id}?`)) {
        // TODO: Implement block user when backend API is available
        console.log('Block user:', this.tweet.user_id);
        alert(`@${this.tweet.user_id} has been blocked`);
        this.showDropdown = false;
      } else {
        this.showDropdown = false;
      }
    },
    reportTweet() {
      // TODO: Implement report tweet functionality
      console.log('Report tweet:', this.tweet.id);
      alert('Thank you. We\'ll review this Tweet.');
      this.showDropdown = false;
    },
    gotoProfile(tweetUserId) {
      this.$router.push({
        name: "Profile",
        params: {
          id: tweetUserId,
        },
      });
    },
    async get() {
      let t = undefined
      if (!this.tweet.parent_id || this.tweet.parent_id === this.tweet.root_id) {
        const getObject = {
          userId: this.tweet.user_id,
          tweetId: this.tweet.id,
        }
        t =  await warpnetService.getTweet(getObject);
      } else {
        const getObject = {
          rootId: this.tweet.root_id,
          replyId: this.tweet.id,
        }
        t =  await warpnetService.getReply(getObject);
      }
      this.showReplyOverlay = true;
    },
    async deleteTweet() {
      if (!this.tweet.parent_id || this.tweet.parent_id === '') {
        const deleteObject = {
          userId: this.tweet.user_id,
          tweetId: this.tweet.id,
        }
        await warpnetService.deleteTweet(deleteObject);
        this.gotoProfile(this.profile.id);
      } else {
        const deleteObject = {
          userId: this.profile.id,
          rootId: this.tweet.root_id,
          replyId: this.tweet.id,
        }
        await warpnetService.deleteReply(deleteObject);
      }
    },
    replyToTweet() {
      this.showReplyOverlay = true;
    },
    async retweet() {
      let retweetsNum = 0
      const retweetObject = {
        tweetId: this.tweet.id,
        userId: this.tweet.user_id,
        username: this.tweet.username,
        text: this.tweet.text,
      }
      const alreadyRetweeted = await warpnetService.hasRetweeter(this.tweet.id, this.profile.id)
      try {
        if (!alreadyRetweeted || this.tweet.retweeted_by === '') {
          retweetsNum = await warpnetService.retweetTweet(retweetObject).catch((err) => {
            console.error(`failed to retweet [${this.tweet.id}]`, err);
          });
        } else {
          retweetsNum = await warpnetService.unretweetTweet(this.tweet.id).catch((err) => {
            console.error(`failed to unretweet [${this.tweet.id}]`, err);
          });
        }
      }catch (err) {
        console.error(`failed to retweet/unretweet tweet [${this.tweet.id}]`, err);
        await this.loadTweetStats(this.tweet.id, this.tweet.user_id);
        return;
      }

      if (!alreadyRetweeted) {
        await warpnetService.setRetweeter(this.tweet.id, this.profile.id, this.profile)
      } else {
        await warpnetService.deleteRetweeter(this.tweet.id, this.profile.id)
      }

      this.retweetsCount.set(this.tweet.id, retweetsNum)
    },
    async like() {
      if (this.tweet.network !== "warpnet") {
        return
      }
      let likesNum = 0
      const alreadyLiked = await warpnetService.hasLiker(this.tweet.id, this.profile.id)
      try {
        if (!alreadyLiked) {
          likesNum = await warpnetService.likeTweet(this.tweet.id, this.tweet.user_id)
        } else {
          likesNum = await warpnetService.unlikeTweet(this.tweet.id, this.tweet.user_id)
        }
      } catch (err) {
        console.error(`failed to like/unlike tweet [${this.tweet.id}]`, err);
        await this.loadTweetStats(this.tweet.id, this.tweet.user_id);
        return;
      }
      if (!alreadyLiked) {
        await warpnetService.setLiker(this.tweet.id, this.profile.id, this.profile)
      } else {
        await warpnetService.deleteLiker(this.tweet.id, this.profile.id)
      }

      this.likesCount.set(this.tweet.id, likesNum);
    },
    getLikesCount(tweetId) {
      return this.likesCount.get(tweetId);
    },
    getRetweetsCount(tweetId) {
      return this.retweetsCount.get(tweetId);
    },
    getRepliesCount(tweetId) {
      return this.repliesCount.get(tweetId);
    },
    async loadTweetStats(tweetId, userId) {
      const stats = await warpnetService.getTweetStats(tweetId, userId);

      this.likesCount.set(stats.tweet_id, stats.likes_count);
      this.retweetsCount.set(stats.tweet_id, stats.retweets_count);
      this.repliesCount.set(stats.tweet_id, stats.replies_count);
      // this.viewsCount.set(stats.tweet_id, stats.views_count); // TODO
    },
    handleClickOutside(event) {
      const dropdown = this.$el.querySelector('.absolute.right-0.mt-2');
      const trigger = this.$el.querySelector('.fa-ellipsis-h');
      if (this.showDropdown && dropdown && !dropdown.contains(event.target) && !trigger.contains(event.target)) {
        this.showDropdown = false;
      }
    }
  },
  mounted() {
    document.addEventListener('click', this.handleClickOutside);
  },
  beforeUnmount() {
    document.removeEventListener('click', this.handleClickOutside);
  },
  async created() {
    console.log("loading component:", this.$options.name);
    console.log("loading tweet:", JSON.stringify(this.tweet));
    this.profile = await warpnetService.getProfile(this.tweet.user_id);

    if (this.tweet.retweeted_by && this.tweet.retweeted_by !== this.profile.id) {
      const retweeter = await warpnetService.getProfile(this.tweet.retweeted_by)
      this.label = `${retweeter.username} Retweeted`;
    }

    this.tweet.image = await warpnetService.getImage({userId: this.tweet.user_id, key: this.tweet.image_key})
    this.profile.avatar = await warpnetService.getImage({userId: this.profile.id, key: this.profile.avatar_key})

    console.log("final tweet:", JSON.stringify(this.tweet));

    await this.loadTweetStats(this.tweet.id, this.tweet.user_id);
  },
};
</script>
