<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div v-if="deleted" class="hidden"></div>
  <div v-if="!deleted && tweet.retweeted_by && tweet.retweeted_by !== ''">
    <!-- Retweet header -->
    <div class="pt-4 pl-4 flex flex-row">
      <div class="w-12 mr-4 flex justify-end">
        <i class="text-sm pt-1 fas fa-retweet text-dark"></i>
      </div>
      <p class="text-sm text-dark">{{ label }}</p>
    </div>
  </div>
  <div
      v-if="!deleted"
      class="w-full p-2 pt-1 pb-1 md:p-4 md:pt-2 md:pb-2 border-b hover:bg-lightest flex"
  >
    <div class="flex-none mr-2 md:mr-4 pt-1">
      <button type="button" @click="gotoProfile(tweet.user_id)" class="flat-btn" aria-label="View profile">
        <img
          :src="profile.avatar || '/default_profile.png'"
          class="h-12 w-12 rounded-full flex-none object-cover bg-transparent"
          :alt="`${tweet.username || 'User'} avatar`"
        />
      </button>
    </div>
    <div class="w-full">
      <div class="flex items-center w-full">
        <button type="button" @click="gotoProfile(tweet.user_id)" class="font-semibold hover:underline flat-btn">
          {{ tweet.username || 'Anonymous' }}
        </button>
        <p class="hidden md:block text-sm text-dark ml-2">
          @{{ tweet.user_id }}
        </p>
        <p class="text-sm text-dark ml-2">·</p>
        <p class="text-sm text-dark ml-2">{{ $filters.timeago(tweet.created_at) }}</p>
        <div v-if="isOwner" class="relative ml-auto">
          <button type="button" @click="showDropdown = !showDropdown" class="rounded-full w-7 h-7 flex items-center justify-center hover:bg-lighter flat-btn" aria-label="Tweet options" :aria-expanded="showDropdown">
            <i class="fas fa-angle-down text-sm text-dark" aria-hidden="true"></i>
          </button>
          <div v-if="showDropdown" class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-10">
            <button type="button" @click="deleteTweet" class="block w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-gray-100 flat-btn">Delete tweet</button>
          </div>
        </div>
      </div>
      <p v-if="!tweet.moderation || tweet.moderation?.is_ok" class="pb-2">
        {{ tweet.text }} 
      </p>
      <p v-else class="pb-2 bg-red-300">
        Moderated: {{ tweet.moderation.reason }}.
      </p>
      <div v-if="tweetImages.length === 1" class="mt-2">
        <img
            :src="tweetImages[0]"
            alt="Tweet image"
            class="rounded-lg max-w-full border border-lighter"
        />
      </div>
      <div v-else-if="tweetImages.length === 2" class="mt-2 grid grid-cols-2 gap-1 rounded-lg overflow-hidden border border-lighter">
        <img v-for="(img, i) in tweetImages" :key="i" :src="img" alt="Tweet image" class="w-full h-48 object-cover" />
      </div>
      <div v-else-if="tweetImages.length === 3" class="mt-2 grid grid-cols-2 gap-1 rounded-lg overflow-hidden border border-lighter" style="height:300px">
        <img :src="tweetImages[0]" alt="Tweet image" class="row-span-2 w-full h-full object-cover" style="grid-row: span 2" />
        <img :src="tweetImages[1]" alt="Tweet image" class="w-full h-full object-cover" />
        <img :src="tweetImages[2]" alt="Tweet image" class="w-full h-full object-cover" />
      </div>
      <div v-else-if="tweetImages.length >= 4" class="mt-2 grid grid-cols-2 gap-1 rounded-lg overflow-hidden border border-lighter">
        <img v-for="(img, i) in tweetImages.slice(0, 4)" :key="i" :src="img" alt="Tweet image" class="w-full h-36 object-cover" />
      </div>
      <div class="flex w-full mt-1">
        <div class="flex items-center text-sm text-dark w-1/4">
          <button
            @click="replyToTweet"
            type="button"
            class="mr-2 rounded-full w-9 h-9 flex items-center justify-center hover:bg-lighter hover:text-blue transition-colors"
            aria-label="Reply"
            title="Reply"
          >
            <i class="far fa-comment" aria-hidden="true"></i>
          </button>
          <p v-if="getRepliesCount(tweet.id) > 0">{{ getRepliesCount(tweet.id) || '?' }}</p>
        </div>
        <div class="flex items-center text-sm text-dark w-1/4">
          <button
            @click="retweet()"
            type="button"
            class="mr-2 rounded-full w-9 h-9 flex items-center justify-center hover:bg-green-100 transition-colors"
            :aria-label="retweeted ? 'Undo retweet' : 'Retweet'"
            :title="retweeted ? 'Undo retweet' : 'Retweet'"
          >
            <i
              class="fas fa-retweet"
              :class="retweeted ? 'text-green-500' : ''"
              aria-hidden="true"
            ></i>
          </button>
          <p v-if="getRetweetsCount(tweet.id) > 0">{{ getRetweetsCount(tweet.id) || '?'}}</p>
        </div>
        <div class="flex items-center text-sm text-dark w-1/4">
          <button
            @click="like()"
            type="button"
            class="mr-2 rounded-full w-9 h-9 flex items-center justify-center hover:bg-red-100 transition-colors"
            :aria-label="liked ? 'Unlike' : 'Like'"
            :title="liked ? 'Unlike' : 'Like'"
          >
            <i class="fas fa-heart" :class="liked ? 'text-red-600' : ''" aria-hidden="true"></i>
          </button>
          <p v-if="getLikesCount(tweet.id) > 0">{{ getLikesCount(tweet.id) }}</p>
        </div>
        <div class="flex items-center text-sm text-dark w-1/4">
          <button type="button" disabled class="rounded-full w-9 h-9 flex items-center justify-center opacity-50 cursor-not-allowed flat-btn" aria-label="Share (coming soon)" title="Coming soon">
            <i class="fas fa-share-square" aria-hidden="true"></i>
          </button>
        </div>
      </div>
    </div>
    <ReplyOverlay
        v-if="showReplyOverlay"
        :tweet="tweet" :profile="profile"
        :showReplyOverlay="showReplyOverlay"
        @close="showReplyOverlay = false"
    />
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: "Tweet",
  props: ["tweet"],
  components: {
    ReplyOverlay: defineAsyncComponent(() => import('./ReplyOverlay.vue'))
  },
  data() {
    return {
      profile: {},
      showReplyOverlay: false,
      showDropdown: false,
      deleted: false,
      isOwner: false,
      label: "You Retweeted",
      liked: false,
      retweeted: false,
      likesCount: new Map(),
      retweetsCount: new Map(),
      repliesCount: new Map(),
      tweetImages: [],
    };
  },
  methods: {
    async refreshInteractionState() {
      const owner = warpnetService.getOwnerProfile();
      if (!owner) {
        this.liked = false;
        this.retweeted = false;
        return;
      }

      this.liked = await warpnetService.hasLiker(this.tweet.id, owner.user_id);
      this.retweeted = this.tweet.retweeted_by === owner.user_id
        || await warpnetService.hasRetweeter(this.tweet.id, owner.user_id);
    },
    gotoProfile(tweetUserId) {
      this.$router.push({
        name: "Profile",
        params: {
          id: tweetUserId,
        },
      });
    },
    async get() {
      let t = undefined
      if (!this.tweet.parent_id || this.tweet.parent_id === this.tweet.root_id) {
        const getObject = {
          userId: this.tweet.user_id,
          tweetId: this.tweet.id,
        }
        t =  await warpnetService.getTweet(getObject);
      } else {
        const getObject = {
          rootId: this.tweet.root_id,
          replyId: this.tweet.id,
        }
        t =  await warpnetService.getReply(getObject);
      }
      this.showReplyOverlay = true;
    },
    async deleteTweet() {
      this.showDropdown = false;
      try {
        if (!this.tweet.parent_id || this.tweet.parent_id === '') {
          await warpnetService.deleteTweet({
            userId: this.tweet.user_id,
            tweetId: this.tweet.id,
          });
        } else {
          await warpnetService.deleteReply({
            userId: this.tweet.user_id,
            rootId: this.tweet.root_id,
            replyId: this.tweet.id,
          });
        }
        this.deleted = true;
        window.location.reload();
      } catch (err) {
        console.error('Failed to delete tweet:', err);
      }
    },
    replyToTweet() {
      this.showReplyOverlay = true;
    },
    async retweet() {
      const owner = warpnetService.getOwnerProfile();
      if (!owner) return;
      const retweetObject = {
        tweetId: this.tweet.id,
        userId: this.tweet.user_id,
        username: this.tweet.username,
        text: this.tweet.text,
      }
      const alreadyRetweeted = this.retweeted
      try {
        if (!alreadyRetweeted) {
          await warpnetService.retweetTweet(retweetObject);
          await warpnetService.setRetweeter(this.tweet.id, owner.user_id, owner)
          this.tweet.retweeted_by = owner.user_id;
          this.retweeted = true;
        } else {
          await warpnetService.unretweetTweet(this.tweet.id);
          await warpnetService.deleteRetweeter(this.tweet.id, owner.user_id)
          this.tweet.retweeted_by = null;
          this.retweeted = false;
        }
      } catch (err) {
        console.error(`failed to retweet/unretweet tweet [${this.tweet.id}]`, err);
      }
      window.location.reload();
    },
    async like() {
      if (this.tweet.network && this.tweet.network !== "warpnet") {
        return
      }
      const owner = warpnetService.getOwnerProfile();
      if (!owner) return;
      let likesNum = 0
      const alreadyLiked = this.liked
      try {
        if (!alreadyLiked) {
          likesNum = await warpnetService.likeTweet(this.tweet.id, this.tweet.user_id)
        } else {
          likesNum = await warpnetService.unlikeTweet(this.tweet.id, this.tweet.user_id)
        }
      } catch (err) {
        console.error(`failed to like/unlike tweet [${this.tweet.id}]`, err);
        await this.loadTweetStats(this.tweet.id, this.tweet.user_id);
        return;
      }
      if (!alreadyLiked) {
        await warpnetService.setLiker(this.tweet.id, owner.user_id, owner)
        this.liked = true;
      } else {
        await warpnetService.deleteLiker(this.tweet.id, owner.user_id)
        this.liked = false;
      }

      this.likesCount.set(this.tweet.id, likesNum);
      window.location.reload();
    },
    getLikesCount(tweetId) {
      return this.likesCount.get(tweetId);
    },
    getRetweetsCount(tweetId) {
      return this.retweetsCount.get(tweetId);
    },
    getRepliesCount(tweetId) {
      return this.repliesCount.get(tweetId);
    },
    async loadTweetStats(tweetId, userId) {
      const stats = await warpnetService.getTweetStats(tweetId, userId);

      this.likesCount.set(stats.tweet_id, stats.likes_count);
      this.retweetsCount.set(stats.tweet_id, stats.retweets_count);
      this.repliesCount.set(stats.tweet_id, stats.replies_count);
      // this.viewsCount.set(stats.tweet_id, stats.views_count); // TODO
    }
  },
  async created() {
    console.log("loading component:", this.$options.name);
    console.log("loading tweet:", JSON.stringify(this.tweet));
    this.profile = await warpnetService.getProfile(this.tweet.user_id);

    if (this.tweet.retweeted_by && this.tweet.retweeted_by !== this.profile.id) {
      const retweeter = await warpnetService.getProfile(this.tweet.retweeted_by)
      this.label = `${retweeter.username} Retweeted`;
    }

    const imageKeys = (this.tweet.image_keys && this.tweet.image_keys.length > 0)
        ? this.tweet.image_keys
        : (this.tweet.image_key ? [this.tweet.image_key] : []);
    for (const key of imageKeys) {
      const img = await warpnetService.getImage({userId: this.tweet.user_id, key});
      if (img) this.tweetImages.push(img);
    }
    this.profile.avatar = await warpnetService.getImage({userId: this.profile.id, key: this.profile.avatar_key})

    console.log("final tweet:", JSON.stringify(this.tweet));

    const owner = warpnetService.getOwnerProfile();
    this.isOwner = owner && owner.user_id === this.tweet.user_id;

    await this.loadTweetStats(this.tweet.id, this.tweet.user_id);

    await this.refreshInteractionState();
  },
};
</script>
