<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div v-if="tweet.retweeted_by && tweet.retweeted_by !== ''">
    <!-- Retweet header -->
    <div class="pt-4 pl-4 flex flex-row">
      <div class="w-12 mr-4 flex justify-end">
        <i class="text-sm pt-1 fas fa-retweet text-dark"></i>
      </div>
      <p class="text-sm text-dark">{{ label }}</p>
    </div>
  </div>
  <div
      class="w-full p-2 pt-1 pb-1 md:p-4 md:pt-2 md:pb-2 border-b hover:bg-lightest flex"
  >
    <div class="flex-none mr-2 md:mr-4 pt-1">
      <a>
        <img
          :src="`${this.profile.avatar || 'default_profile.png'}`"
          class="h-12 w-12 rounded-full flex-none"
        />
      </a>
    </div>
    <div class="w-full">
      <div class="flex items-center w-full">
        <a @click="gotoProfile(tweet.user_id)">
          <p class="font-semibold" >{{ tweet.username || 'Anonymous' }}</p>
        </a>
        <p class="hidden md:block text-sm text-dark ml-2">
          @{{ tweet.user_id }}
        </p>
        <p class="text-sm text-dark ml-2">·</p>
        <p class="text-sm text-dark ml-2">{{ $filters.timeago(tweet.created_at) }}</p>
        <div>
          <i @click="showDropdown = !showDropdown" class="fas fa-angle-down text-sm ml-auto text-dark cursor-pointer"></i>
          <div v-if="showDropdown" class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1">
            <a @click="deleteTweet" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Delete tweet</a>
          </div>
        </div>
      </div>
      <p v-if="!tweet.moderation || tweet.moderation.is_ok" class="pb-2">
        {{ tweet.text }} 
      </p>
      <p v-else class="pb-2 bg-red-300">
        Moderated: {{ tweet.moderation.reason }}.
      </p>
      <div v-if="tweet.image" class="mt-2">
        <img
            :src="tweet.image"
            alt="Tweet image"
            class="rounded-lg max-w-full border border-lighter"
        />
      </div>
      <div class="flex w-full">
        <div class="flex items-center text-sm text-dark w-1/4">
          <button
            @click="replyToTweet"
            class="mr-2 rounded-full hover:bg-lighter"
          >
            <i class="far fa-comment"></i>
          </button>
          <p v-if="getRepliesCount(tweet.id) > 0">{{ getRepliesCount(tweet.id) || '?' }}</p>
        </div>
        <div class="flex items-center text-sm text-dark w-1/4">
          <button
            @click="retweet()"
            class="mr-2 rounded-full hover:bg-lighter"
          >
            <i
              :class="
                `fas fa-retweet ${tweet.retweeted_by ? 'text-green-500' : ''}`
              "
            ></i>
          </button>
          <p v-if="getRetweetsCount(tweet.id) > 0">{{ getRetweetsCount(tweet.id) || '?'}}</p>
        </div>
        <div class="flex items-center text-sm text-dark w-1/4">
          <button
            @click="like()"
            class="mr-2 rounded-full hover:bg-lighter"
          >
            <i :class="`fas fa-heart ${getLikesCount(tweet.id) > 0 ? 'text-red-600' : ''}`"></i>
          </button>
          <p v-if="getLikesCount(tweet.id) > 0">{{ getLikesCount(tweet.id) }}</p>
        </div>
        <div class="flex items-center text-sm text-dark w-1/4">
          <i class="fas fa-share-square mr-3 cursor-not-allowed"></i>
        </div>
      </div>
    </div>
    <ReplyOverlay
        v-if="showReplyOverlay"
        :tweet="tweet" :profile="profile"
        :showReplyOverlay="showReplyOverlay"
        @close="showReplyOverlay = false"
    />
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: "Tweet",
  props: ["tweet"],
  components: {
    ReplyOverlay: defineAsyncComponent(() => import('./ReplyOverlay.vue'))
  },
  data() {
    return {
      profile: {},
      showReplyOverlay: false,
      showDropdown: false,
      label: "You Retweeted",
      likesCount: new Map(),
      retweetsCount: new Map(),
      repliesCount: new Map(),
    };
  },
  methods: {
    gotoProfile(tweetUserId) {
      this.$router.push({
        name: "Profile",
        params: {
          id: tweetUserId,
        },
      });
    },
    async get() {
      let t = undefined
      if (!this.tweet.parent_id || this.tweet.parent_id === this.tweet.root_id) {
        const getObject = {
          userId: this.tweet.user_id,
          tweetId: this.tweet.id,
        }
        t =  await warpnetService.getTweet(getObject);
      } else {
        const getObject = {
          rootId: this.tweet.root_id,
          replyId: this.tweet.id,
        }
        t =  await warpnetService.getReply(getObject);
      }
      this.showReplyOverlay = true;
    },
    async deleteTweet() {
      if (!this.tweet.parent_id || this.tweet.parent_id === '') {
        const deleteObject = {
          userId: this.tweet.user_id,
          tweetId: this.tweet.id,
        }
        await warpnetService.deleteTweet(deleteObject);
        this.gotoProfile(this.profile.id);
      } else {
        const deleteObject = {
          userId: this.profile.id,
          rootId: this.tweet.root_id,
          replyId: this.tweet.id,
        }
        await warpnetService.deleteReply(deleteObject);
      }
    },
    replyToTweet() {
      this.showReplyOverlay = true;
    },
    async retweet() {
      let retweetsNum = 0
      const retweetObject = {
        tweetId: this.tweet.id,
        userId: this.tweet.user_id,
        username: this.tweet.username,
        text: this.tweet.text,
      }
      const alreadyRetweeted = await warpnetService.hasRetweeter(this.tweet.id, this.profile.id)
      try {
        if (!alreadyRetweeted || this.tweet.retweeted_by === '') {
          retweetsNum = await warpnetService.retweetTweet(retweetObject).catch((err) => {
            console.error(`failed to retweet [${this.tweet.id}]`, err);
          });
        } else {
          retweetsNum = await warpnetService.unretweetTweet(this.tweet.id).catch((err) => {
            console.error(`failed to unretweet [${this.tweet.id}]`, err);
          });
        }
      }catch (err) {
        console.error(`failed to retweet/unretweet tweet [${this.tweet.id}]`, err);
        await this.loadTweetStats(this.tweet.id, this.tweet.user_id);
        return;
      }

      if (!alreadyRetweeted) {
        await warpnetService.setRetweeter(this.tweet.id, this.profile.id, this.profile)
      } else {
        await warpnetService.deleteRetweeter(this.tweet.id, this.profile.id)
      }

      this.retweetsCount.set(this.tweet.id, retweetsNum)
    },
    async like() {
      if (this.tweet.network !== "warpnet") {
        return
      }
      let likesNum = 0
      const alreadyLiked = await warpnetService.hasLiker(this.tweet.id, this.profile.id)
      try {
        if (!alreadyLiked) {
          likesNum = await warpnetService.likeTweet(this.tweet.id, this.tweet.user_id)
        } else {
          likesNum = await warpnetService.unlikeTweet(this.tweet.id, this.tweet.user_id)
        }
      } catch (err) {
        console.error(`failed to like/unlike tweet [${this.tweet.id}]`, err);
        await this.loadTweetStats(this.tweet.id, this.tweet.user_id);
        return;
      }
      if (!alreadyLiked) {
        await warpnetService.setLiker(this.tweet.id, this.profile.id, this.profile)
      } else {
        await warpnetService.deleteLiker(this.tweet.id, this.profile.id)
      }

      this.likesCount.set(this.tweet.id, likesNum);
    },
    getLikesCount(tweetId) {
      return this.likesCount.get(tweetId);
    },
    getRetweetsCount(tweetId) {
      return this.retweetsCount.get(tweetId);
    },
    getRepliesCount(tweetId) {
      return this.repliesCount.get(tweetId);
    },
    async loadTweetStats(tweetId, userId) {
      const stats = await warpnetService.getTweetStats(tweetId, userId);

      this.likesCount.set(stats.tweet_id, stats.likes_count);
      this.retweetsCount.set(stats.tweet_id, stats.retweets_count);
      this.repliesCount.set(stats.tweet_id, stats.replies_count);
      // this.viewsCount.set(stats.tweet_id, stats.views_count); // TODO
    }
  },
  async created() {
    console.log("loading component:", this.$options.name);
    this.profile = await warpnetService.getProfile(this.tweet.user_id);

    if (this.tweet.retweeted_by && this.tweet.retweeted_by !== this.profile.id) {
      const retweeter = await warpnetService.getProfile(this.tweet.retweeted_by)
      this.label = `${retweeter.username} Retweeted`;
    }

    this.tweet.image = await warpnetService.getImage({userId: this.tweet.user_id, key: this.tweet.image_key})
    this.profile.avatar = await warpnetService.getImage({userId: this.profile.id, key: this.profile.avatar_key})

    await this.loadTweetStats(this.tweet.id, this.tweet.user_id);
  },
};
</script>
