<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div class="w-full px-4 py-2 border-b hover:bg-lightest flex flex-row">
    <div class="flex-none">
      <a @click="pushToProfilePage(user.id)">
        <img
          :src="`${user.avatar || 'default_profile.png'}`"
          class="h-12 w-12 rounded-full"
         />
      </a>
    </div>
    <div class="ml-2 flex flex-col w-full">
      <div class="flex flex-row justify-between w-full">
        <div class="flex flex-col">

          <p v-if="!user.moderation || user.moderation.is_ok">
            <p class="font-bold">{{ user.username }}</p>
          </p>
          <p v-else>
            <p class="font-bold">Moderated</p>
          </p>
          <p class="text-dark text-sm">@{{ user.id }}</p>
        </div>
        <div v-if="profile && profile.id !== user.id">
          <button
            v-if="!user.following"
            @click="follow"
            class="ml-auto text-blue font-bold px-4 py-1 rounded-full border border-blue mb-2 hover:bg-lightblue"
          >
            Follow
          </button>
          <button
            v-if="user.following"
            @mouseover="followingLabel = 'Unfollow'"
            @mouseleave="followingLabel = 'Following'"
            @click="unfollow"
            class="ml-auto text-white bg-blue font-bold px-4 py-1 rounded-full border mb-2 hover:bg-red-700"
          >
            {{ followingLabel }}
          </button>
        </div>
      </div>
      <div>
        <p>{{ user.bio }}</p>
        <p v-if="!user.moderation || user.moderation.is_ok">
          {{ user.bio }}
        </p>
        <p v-else class="pb-2 bg-red-300">
          Moderated: {{ user.moderation.reason }}
        </p>
      </div>
    </div>
  </div>
</template>

<script>
import {warpnetService} from "@/service/service";

export default {
  name: "User",
  props: {
    user: {
      id: "",
      username: "",
      type: Object,
      required: true,
      avatar: "",
      following: false,
    }
  },
  data() {
    return {
      followingLabel: "Following",
      profile: {},
    };
  },
  methods: {
    async follow() {
      try {
        await warpnetService.followUser(this.user.id);
        this.user.following = true;
      } catch (err) {
        console.error(`failed to follow [${this.user.id}]`, err);
      }
    },
    async unfollow() {
      try {
        await warpnetService.unfollowUser(this.user.id);
        this.user.following = false;
      } catch (err) {
        console.error(`failed to unfollow [${this.user.id}]`, err);
      }
    },
    async pushToProfilePage(profileId) {
      this.$router.push({
        name: "Profile",
        params: {
          id: profileId
        }
      });
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);
    this.profile = warpnetService.getOwnerProfile();
    this.profile.background_image = await warpnetService.getImage({userId:this.profile.id, key:this.profile.background_image_key});
    this.profile.avatar = await warpnetService.getImage({userId:this.profile.id, key:this.profile.avatar_key})
    this.user.avatar = await warpnetService.getImage({userId:this.user.id, key:this.user.avatar_key})
  },
};
</script>
