<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div class="w-full rounded-lg bg-lightest my-4">
    <div class="p-3">
      <p class="text-lg font-bold">Who to follow</p>
    </div>
    <div v-if="profile" v-for="profile in profiles" :key="profile.id" class="w-full flex hover:bg-lighter p-3 border-t border-lighter">
      <img 
        @click="pushToProfilePage(profile.id)" 
        :src="profile.avatar || '/default_profile.png'"
        class="w-12 h-12 rounded-full cursor-pointer object-cover bg-transparent"
        :alt="profile.username"
      />
      <div class="hidden lg:block ml-4">
        <p @click="pushToProfilePage(profile.id)" class="text-left text-sm font-bold leading-tight cursor-pointer">{{ profile.username }}</p>
        <p class="text-left text-sm leading-tight text-dark">{{ profile.id.slice(0, 8) }}...</p>
      </div>
      <button
        v-if="!isFollowing(profile.id)"
        @click="follow(profile.id)" 
        class="ml-auto text-sm text-blue font-bold px-4 py-1 rounded-full border border-blue m-2"
      >
        Follow
      </button>
      <button
          v-if="isFollowing(profile.id)"
          @click="unfollow(profile.id)"
          class="ml-auto text-sm text-blue font-bold px-4 py-1 rounded-full border border-blue m-2"
      >
        Unfollow
      </button>
    </div>
    <button
        @click="loadMore()"
        class="p-3 w-full hover:bg-lighter text-left text-blue border-t border-lighter"
    >
      Show More
    </button>
  </div>
</template>

<script>
import {warpnetService} from "@/service/service";

export default {
  name: 'WhoToFollow',
  props: ["profile"],
  data() {
    return {
      ownerProfile: undefined,
      profiles: [],
      followingStatus: new Map(),
    };
  },
  methods: {
    async pushToProfilePage(profileId) {
      this.$router.push({ 
        name: "Profile",
        params: {
          id: profileId
        }
      });
    },
    isFollowing(profileId) {
      return this.followingStatus.get(profileId) || false
    },
    async follow(profileId) {
      await warpnetService.followUser(profileId);
      this.followingStatus.set(profileId, true)
    },
    async unfollow(profileId) {
      await warpnetService.unfollowUser(profileId);
      this.followingStatus.set(profileId, false)
    },
    async loadAvatars(profiles) {
      await Promise.all(
        profiles.map(async (p) => {
          p.avatar = await warpnetService.getImage({userId: p.id, key: p.avatar_key});
        })
      );
      this.profiles = [...this.profiles];
    },
    async loadMore() {
      const effectiveProfile = this.profile || this.ownerProfile;
      const profileId = effectiveProfile?.id || effectiveProfile?.user_id;
      const users = await warpnetService.getWhoToFollow(profileId, false)
      for (const p of users) {
        const status = await warpnetService.isFollowing(p.id);
        this.followingStatus.set(p.id, status);
      }
      this.profiles = [...this.profiles, ...users];
      await this.loadAvatars(users);
    },
   },
  async created() {
    console.log("loading component:", this.$options.name);
    this.ownerProfile = warpnetService.getOwnerProfile();
    const effectiveProfile = this.profile || this.ownerProfile;
    const profileId = effectiveProfile?.id || effectiveProfile?.user_id;
    this.profiles = await warpnetService.getWhoToFollow(profileId, true)
    for (const p of this.profiles) {
      const status = await warpnetService.isFollowing(p.id);
      this.followingStatus.set(p.id, status);
    }
    await this.loadAvatars(this.profiles);
  },
};
</script>